- package.json
- src/handlers/mesh_gateway_handlers.ts
- src/index.ts
- src/logger.ts
- src/runners/http_service_runner.ts
- src/runners/order_watcher_service_runner.ts
- src/runners/websocket_service_runner.ts
- src/services/websocket_service.ts
- src/utils/schema_utils.ts
- yarn.lock
`console.log` is OK, but pino is way nicer.
> Use pino as a logger

- Dockerfile
- docker-compose.yml
- package.json
- src/index.ts
- yarn.lock
- It can take a while to connect and sync with mesh, and there is no need to block the addition of express routes until then. 
- The forever module is no longer necessary because k8s will take care of restarts.
> More startup improvements

- docker-compose.yml
- src/services/staking_data_service.ts
- src/types.ts
- src/utils/staking_utils.ts
I also updated the events-pipeline image so we have meta-data now!
Open to improvements in naming here...
> Add 7 day generated protocol fees to the staking API response

- docker-compose.yml
Very tiny PR to update Mesh to latest version.
> update mesh version

- src/handlers/staking_handlers.ts
- src/routers/staking_router.ts
- src/services/staking_data_service.ts
- src/types.ts
- src/utils/staking_utils.ts
Example response
GET `/staking/delegator/0xdeadbeef`
```json
{
"delegatorAddress": "0xdeadbeef",
"forCurrentEpoch": {
"zrxDeposited": 100,
"zrxStaked": 100,
"poolData": [
{
"poolId": "2",
"zrxStaked": 100
}
]
},
"forNextEpoch": {
"zrxDeposited": 100,
"zrxStaked": 100,
"poolData": [
{
"poolId": "2",
"zrxStaked": 100
}
]
},
"allTime": {
"poolData": [
{
"poolId": "2",
"rewardsInEth": 0.06200487931017588
}
]
}
}
```
> Delegator stats endpoint

- src/handlers/staking_handlers.ts
- src/queries/staking_queries.ts
- src/routers/staking_router.ts
- src/services/staking_data_service.ts
- src/types.ts
- src/utils/staking_utils.ts
**Example request:** GET /staking/pools/2
**Response:**
```json
{
"poolId": "2",
"stakingPool": {
"poolId": "2",
"operatorAddress": "0x6ecbe1db9ef729cbe972c83fb886247691fb6beb",
"createdAt": {
"blockNumber": 14576829,
"txHash": "0x4d587b256b712a456cca2297d599460942444f0cf04774fe48d380b06e89bfb0"
},
"metaData": {
"name": "Magical Market Making Machine (MMM)",
"bio": "All your stake are belong to us",
"location": "San Francisco, CA",
"isVerified": false,
"logoUrl": "https://github.com/0xProject/0x-staking-pool-registry/raw/master/logos/0x.png",
"websiteUrl": "http://0x.org"
},
"allTimeStats": {
"operatorRewardsPaidInEth": 1.24010006641e-7,
"membersRewardsPaidInEth": 0.06200487931017588,
"totalRewardsPaidInEth": 0.06200500332018252,
"protocolFeesGeneratedInEth": 0.00975
},
"epochRewards": [ …
```
> Staking pool by id endpoint

- src/logger.ts
```
{"level":"info","time":1576203164120,"pid":78400,"hostname":"0x","msg":"API (HTTP) listening on port 3000!\nConfig: {\n  \"WHITELISTED_TOKENS\": [\n    \"0x2002d3812f58e35f0ea1ffbf80a75a38c32175fa\",\n    \"0xd0a1e359811322d97991e03f863a0c30c2cf029c\"\n  ],\n  \"HTTP_PORT\": 3000,\n  \"CHAIN_ID\": 42,\n  \"MESH_WEBSOCKET_URI\": \"ws://localhost:60557\",\n  \"FEE_RECIPIENT_ADDRESS\": \"0x0000000000000000000000000000000000000000\",\n  \"MAKER_FEE_UNIT_AMOUNT\": \"0\",\n  \"TAKER_FEE_UNIT_AMOUNT\": \"0\",\n  \"MAKER_FEE_ASSET_DATA\": \"0x\",\n  \"TAKER_FEE_ASSET_DATA\": \"0x\",\n  \"POSTGRES_URI\": \"postgresql://api:api@localhost/api\",\n  \"MAX_PER_PAGE\": 1000,\n  \"DEFAULT_ERC20_TOKEN_PRECISION\": 18\n}","v":1}
```
> Use logLevelLabels option

- src/errors.ts
- src/middleware/error_handling.ts
Resolves #35
Before:
After:
Tested a bit on Kovan and staging, but not exhaustively.
> improve runtime error handling

- src/handlers/sra_handlers.ts
- src/routers/sra_router.ts
> Add docs link to root of SRA API

- src/queries/staking_queries.ts
Fixed the formatting of the overall stats query (had to eliminate extra semicolons).
> fixed formatting on stats query

- src/constants.ts
- src/services/sra_http_service.ts
As described here: https://0xproject.quip.com/btQsAya3ZD0h/0x-API-Versioning-Scoping-Doc#aeHACAsgoR1
I will implement `/sra/*` -> `/sra/v3/*` in k8s.
> Add versions to API paths

- src/types.ts
- src/utils/staking_utils.ts
Was actually returning a boolean type, not a string. Updated code to reflect that.
> Fixes verified boolean conversion for staking pool verification

- src/types.ts
- src/utils/staking_utils.ts
**TODO:** Needs some frontend work to handle the cases where operator share is missing
> Handle null pool operator share

- src/config.ts
- src/constants.ts
- src/handlers/swap_handlers.ts
- src/middleware/error_handling.ts
- src/middleware/request_logger.ts
- src/services/swap_service.ts
- src/types.ts
- src/utils/token_metadata_utils.ts
There was a cyclic import dependency between `constants` and `config`. This resulted in unexpected `undefined` when `constants` attempted to read `config` (`CHAIN_ID` was undefined). Resulting in Bridges being disabled.
Previously 
```json
{
"level": "info",
"time": 1578871838735,
"pid": 44899,
"hostname": "Macintosh-2.local",
"req": {
"url": "/swap/quote",
"method": "GET",
...
},
"body": {},
"params": {},
"query": {
"buyToken": "WETH",
"sellToken": "DAI",
"buyAmount": "1000000000000000000000"
}
},
"res": {
"statusCode": 400,
"statusMessage": "Bad Request"
},
"responseTime": 4381,
"timestamp": 1578871838735,
"v": 1
}
```
Now
```json
{
"level": "info",
"time": 1578873524070,
"pid": 61012,
"hostname": "Macintosh-2.local",
"req": {
"url": "/swap/v0/quote",
"method": "GET",
...
},
"body": {}, …
```
> Clean up errors, tokens

- src/services/swap_service.ts
- src/types.ts
```
{
"price": "163",
"to": "0x61935cbdd02287b511119ddb11aeb42f1593b7ef",
"data": "0x8bc8efb3000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000002540be4000000000000000000000000000000000000000000000000000000000000000340000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000008fd0155f564d5021bb0755a97b358b26323103f50000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a258b39954cef5cb142fd567a46cddb31a670124000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a27756ffd26e710000000000000000000000000000000000000000000000006771fc64e2fc51f3000 …
```
> Fixed price and change sellAmount and buyAmount labels

- docker-compose.yml
- package.json
- src/services/order_watcher_service.ts
- yarn.lock
We upgraded the mesh deployment to 8x but didn't upgrade the mesh-rpc-client.
> Upgrade mesh-rpc-client to 8.1.0

- README.md
Only the first wave of improvements. Waiting for runners in #50 to add more.
> Slightly improve README

- src/runners/order_watcher_service_runner.ts
Would be useful to have these as nicely formatted for alerting.
> Add uncaughtException and unhandledRejection to order_watcher_service_runner

- src/runners/order_watcher_service_runner.ts
- src/services/swap_service.ts
```
{
code: 105,
reason: "CompleteBuyFailedError",
values: {
expectedAssetBuyAmount: "100000000000000000000",
actualAssetBuyAmount: "0"
}
}
```
> Revert on not enough eth

- src/constants.ts
- src/handlers/sra_handlers.ts
- src/handlers/swap_handlers.ts
- src/routers/swap_router.ts
Docs https://github.com/0xProject/website/pull/218
```
 {"message":"This is the root of the Swap API. Visit https://0x.org/docs/api#swap for details about this API."}
```
```
{"message":"This is the root of the Standard Relayer API. Visit https://0x.org/docs/api#sra for details about this API."}
```
```
{
"records": [
{
"symbol": "DAI",
"address": "0x6b175474e89094c44da98b954eedeac495271d0f",
"name": "Dai Stablecoin",
"decimals": 18
},
{
"symbol": "REP",
"address": "0x1985365e9f78359a9B6AD760e32412f4a445E862",
"name": "Augur Reputation",
"decimals": 18
},
{
"symbol": "WETH",
"address": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
"name": "Wrapped Ether",
"decimals": 18
},
{
"symbol": "ZRX",
"address": "0xe41d2489571d322189246dafa5ebde1f4699f498",
"name": "0x Protocol Token",
"decimals": …
```
> Add more meta-data to tokens response and add more doc responses

- package.json
- src/config.ts
- src/token_metadatas_for_networks.ts
- yarn.lock
I'm seeing `WETH`, `MKR`, `REP`, `ZRX`, `BAT`, `SAI` and maybe more liquidity.
I'm not seeing any liquidity for `USDC`. I don't think `USDC` is really used that much (?) but the lack of `DAI` is concerning. 
For `buyToken=DAI` queries I get an "out of Gas" error (not seen here). For `sellToken=DAI` queries it works.
```
Error: VM execution error.
at SwapHandlers.<anonymous> (/Users/francescoagosti/Projects/0x-api/src/handlers/swap_handlers.ts:82:23)
at Generator.throw (<anonymous>)
at rejected (/Users/francescoagosti/Projects/0x-api/src/handlers/swap_handlers.ts:5:65)
at processTicksAndRejections (internal/process/next_tick.js:81:5)
```
By disabling kyber we no longer get the DAI errors.
> Enable Kovan bridge liquidity

- src/handlers/swap_handlers.ts
> [Bug fix] Fix excludedSources to use "0x" instead of "native"

- src/handlers/sra_handlers.ts
- src/schemas/schemas.ts
- src/schemas/sra_post_order_request_schema.json
Add a new json schema to validate the post body for `/sra/orders` ensuring strings are passed.
> /sra/orders POST schema validation

- src/constants.ts
- src/services/swap_service.ts
Increases the Order expiration threshold from 30s to 90s.
Add an additional 20% gas limit buffer
> [Reverts] Increase Expiration Threshold and add Gas limit buffer

- .circleci/config.yml
Whoops, we forgot to do this as part of #113
> Update mesh version on CI

- README.md
- package.json
This is mostly required to have somewhere to link to for launch-kit
> Add instructions on using ganache

- package.json
- yarn.lock
> Upgrade to AssetSwapper 4.3.2

- src/handlers/staking_handlers.ts
- src/queries/staking_queries.ts
- src/routers/staking_router.ts
- src/services/staking_data_service.ts
- src/types.ts
- src/utils/staking_utils.ts
Added endpoint for delegator events.
Events include:
- staked
- removed stake
- moved stake
- deposited ZRX
- withdrew ZRX
- earned rewards
Testing:
> Added delegator/events/<address> endpoint

- .circleci/config.yml
- docker-compose.yml
- package.json
- yarn.lock
No interface changes: https://github.com/0xProject/0x-mesh/blob/master/CHANGELOG.md
> Update mesh to 9.2.1

- package.json
- yarn.lock
Redeployed Curve with GST support
> Updated contract-addresses

- package.json
- yarn.lock
https://github.com/0xProject/0x-monorepo/pull/2521
https://github.com/0xProject/0x-monorepo/pull/2533
> Fix Prices and new Forwarder function

- src/constants.ts
> [Fix] Update WETH/ETH unwrapping/wrapping constants

- package.json
- yarn.lock
Combines multiple on-chain sources into a single order, and therefor a single protocol fee. Also frees gas tokens when used.
> Publish DexForwarderBridge

- package.json
- yarn.lock
Allows for a single entrypoint to free GasTokens.
> Use DexForwarderBridge always

- .github/workflows/main.yml
We've adding a staging kovan deployment, this PR adds the `kovan-staging` to deployment workflows.
> Add kovan-staging to workflows

- src/queries/staking_queries.ts
Changed the field name in the events query to conform with the expected raw output.
> [Fix] event => event_type

- src/utils/service_utils.ts
This is super noisy right now.
> replace error with warn when unable to fetch token decimals

- package.json
- src/services/swap_service.ts
- test/app_test.ts
- yarn.lock
Warning log entries emitted by asset-swapper were being lost because they were produced via `logUtils.log()` and so weren't JSON-formatted, so they weren't getting picked up by Kibana.
This depends on https://github.com/0xProject/0x-monorepo/pull/2562
While the test doesn't explicitly verify that the logging is working properly, you can see the warning entry in the test output (even in CI):
```
{"level":"warn","time":1587604950565,"pid":5157,"hostname":"3a4d746c1558","msg":"Failed to get RFQ-T indicative quote from market maker endpoint https://mock-rfqt1.club for API key koolApiKey1 for taker address 0x6ecbe1db9ef729cbe972c83fb886247691fb6beb","v":1}
{"level":"warn","time":1587604950565,"pid":5157,"hostname":"3a4d746c1558","isAxiosError":true,"config":{"url":"https://mock-rfqt1.club/price …
```
> Fix logging for RFQ-T

- .gitignore
- docker-compose.yml
- test/utils/deployment.ts
> fix: Linux compatibility issue

- .github/workflows/release.yml
- CHANGELOG.md
- PULL_REQUEST_TEMPLATE.md
- README.md
- test/app_test.ts
- test/utils/deployment.ts
- Update README with a Release section.
- Add shields because it looks cool.
- Update release logic to deploy to all environments.
- Bump dependency log timeout to 3min.
> chore: Add documentation about release, and make release update all deploy envs

- package.json
- yarn.lock
https://github.com/0xProject/0x-monorepo/pull/2575
`LINK/MKR/DAI/USDC/ETH`
> feat: Remove Kyber exclusion

- src/utils/token_metadata_utils.ts
- test/constants.ts
- test/swap_test.ts
Introduced https://github.com/0xProject/0x-api/commit/06bc402d67065797d587df0675045cbb9554f7dc#diff-af5b2622d5ba7c676f4f280617dcdce5L62
> fix: re-allow unknown tokens to be queried in the swap/quote endpoint

- src/handlers/meta_transaction_handlers.ts
- src/services/transaction_watcher_signer_service.ts
- src/types.ts
- src/utils/signer.ts
This PR:
- fixes an issue where the signer would not sign and broadcast subsequent transactions if it failed to sign and broadcast one of them.
- adds a `cancelled` (naming?) state - a transaction is considered cancelled when the signer failed to sign and broadcast it in a given time (currently `100 s` which might be an overkill)
> refactor: Transaction Signing improvements

- src/handlers/staking_handlers.ts
- src/queries/staking_queries.ts
- src/routers/staking_router.ts
- src/services/staking_data_service.ts
Added an endpoint to supply an arbitrary epoch number and obtain epoch info.
> feat: added an epochs/n endpoint to get info on an arbitrary epoch

- .prettierignore
> chore: make prettier ignore automatically generated CHANGELOG.md

- src/constants.ts
Disable skipping RFQt request where `buyAmount` is specified instead of just `sellAmount`.
Simple config change, no new tests should be required. In a test deployment, should poll RFQt servers when `buyAmount` is specified in `swap/quote` and `swap/price`.
> feat: set default skip RFQt buy requests to false

- test/transaction_watcher_signer_test.ts
> fix(tests): remove .only from transaction_watcher_signer_test.ts

- src/handlers/meta_transaction_handlers.ts
- src/services/meta_transaction_service.ts
Attribute the Metatxn calldata to the affiliate when provided, or 0xAPI as a default.
> fix: Attribute Metatxn calldata to affiliate

- src/handlers/meta_transaction_handlers.ts
- src/services/meta_transaction_service.ts
- src/types.ts
- test/meta_transaction_test.ts
We want to communicate exactly how much money we're saving users in the meta-txn endpoint too. This is a bit different than the regular endpoint:
- We don't need to tell them about the refund they would potentially be getting with gas tokens.
- The estimates don't need to be as accurate.
- We can use `protocolFee` instead of `minimumProtocolFee`.
> feat: add transaction price information to meta-txn endpoints for UI

- package.json
- src/config.ts
- test/meta_transaction_test.ts
- test/rfqt_test.ts
- test/swap_test.ts
- test/utils/mocks.ts
- yarn.lock
Update gitpkg deps to add MultiBridge support. 
Add MultiBridge to gas schedule (6.5e5)
-   [x] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. **Website Documentation PR:** https://github.com/0xProject/website/pull/306
> feat: Add support for MultiBridge

- package.json
- yarn.lock
> fix: uniswap v2 buys

- package.json
- yarn.lock
> fix: asset swapper monorepo f14b6f2ba

- src/services/transaction_watcher_signer_service.ts
Adds a simple liveness gauge for `TransactionWatcherSigner`
> feat: add signer liveness status gauge

- src/token_metadatas_for_networks.ts
Adds Compound token (COMP) to the 0x API metadatas.
> feat: Add Compound token to 0x API aliases

- package.json
- test/rfqt_test.ts
- yarn.lock
> fix: Fix parameters sent off to RFQT providers to be unescaped

- src/services/swap_service.ts
Prevent the sampler being queried for tokens which aren't relevant to the network.
```json
{
"records": [
{
"symbol": "DAI",
"price": "0.004393625785289904"
},
{
"symbol": "REP",
"price": "0.076538996520002342"
},
{
"symbol": "ZRX",
"price": "0.001540893389947478"
},
{
"symbol": "USDC",
"price": "0.004377"
},
{
"symbol": "BAT",
"price": "0.001012320828012612"
},
{
"symbol": "MKR",
"price": "2.291829546186608791"
},
{
"symbol": "WBTC",
"price": "41.0183714"
},
{
"symbol": "SNX",
"price": "0.005889644261233945"
},
{
"symbol": "SUSD",
"price": "0.004335665696650417"
},
{
"symbol": "KNC",
"price": "0.005649200762120254"
},
{
"symbol": "BNT",
"price": "0.00382540038818005"
},
{
"symbol": "GNO",
"price": "0.132973201495201436"
},
{
"symbol": "LINK",
"price": "0.018326004433407458"
},
{ …
```
> fix: filter tokens in prices which do not exist on the network

- src/token_metadatas_for_networks.ts
Adds Universal Market Access (UMA) token to the 0x API metadata registry
> feat: Add UMA token to 0x API metadata registry

- package.json
- yarn.lock
> fix: revert package version change

- src/utils/signer.ts
Removing the local tracking of nonces and rely on the ethereum node to be the source of truth.
> fix: remove NonceTrackerSubprovider

- package.json
- src/constants.ts
- src/utils/gas_station_utils.ts
- yarn.lock
https://github.com/0xProject/0x-monorepo/pull/2614
> fix: Update to ethgasstation proxy endpoint

- package.json
- src/config.ts
- src/constants.ts
- src/services/meta_transaction_service.ts
- src/services/swap_service.ts
- src/utils/gas_station_utils.ts
- yarn.lock
> fix: specify ethgasstation url

- package.json
- src/services/swap_service.ts
- yarn.lock
Work around for Forwarder buy: https://github.com/0xProject/0x-monorepo/pull/2618
Reduce EGS polling: https://github.com/0xProject/0x-monorepo/pull/2619
> fix: egs polling and forwarder buy

- src/token_metadatas_for_networks.ts
Adds BZRX to 0x API token registry
> feat: Add BZRX to 0x API token registry

- src/token_metadatas_for_networks.ts
Uses the new BZRX token address now that the team has released the new address -- https://twitter.com/bzxHQ/status/1282124193664864263
> feat: Updates BZRX token address to new BZRX token

- package.json
- src/app.ts
- src/services/websocket_service.ts
- yarn.lock
> chore: upgrade to typescript 3.9.6

- src/token_metadatas_for_networks.ts
Adds renBTC to the 0x API token metadata registry
**Open questions: Should symbol be RENBTC or renBTC? Does the 0x API already normalize different casing on symbol @dekz ?**
> feat: Add renBTC to 0x API token registry 

- src/token_metadatas_for_networks.ts
Adds $BAL, $LEND, $YFI, $AMPL, and $KEEP to 0x API token registry.
> feat: Add DeFi tokens to 0x API token metadata registry

- src/token_metadatas_for_networks.ts
Updates YFI token decimal to the correct value (18).
> fix: Fixes yearn.finance (YFI) token to have correct decimals

- package.json
- src/config.ts
- yarn.lock
Deploys UniswapV2 bridge on Kovan
https://github.com/0xProject/0x-monorepo/pull/2652
> fix: Kovan deploy UniswapV2

- package.json
- yarn.lock
https://github.com/0xProject/0x-monorepo/pull/2654
Fixes a regression in asset-swapper where sources were collapsed resulting in a lack of split on that source.
> fix: source regression

- src/utils/market_depth_utils.ts
- test/market_depth_test.ts
Returns the input values rather than the output values. This is better aligned with the way it is to be used.
For example, sell BAL, buy DAI, it returns the price and the amount of BAL that can be sold at that price.
You can take that amount and perform a swap quote either selling or buying the amount returned.. 
Previous it returned the amount of DAI available at that price.
> fix: return input in depth-chart

- package.json
- yarn.lock
> chore: update @0x/contract-addresses gitpkg version

- src/handlers/swap_handlers.ts
- src/utils/service_utils.ts
- test/service_utils_test.ts
Adds further excluded sources, if API key is not passed in.
-   [X] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. **Website Documentation PR:**
-   [X] Prefix PR title with `[WIP]` if necessary.
-   [X] Add tests to cover changes as needed.
-   [x] Test on staging
> fix: Update Excluded Sources

- package.json
- yarn.lock
https://github.com/0xProject/0x-monorepo/pull/2655
> fix: update asset-swapper optimizer for splits

- src/constants.ts
- src/handlers/swap_handlers.ts
- src/schemas/swap_quote_request_schema.json
- src/services/swap_service.ts
- src/types.ts
- src/utils/service_utils.ts
- test/service_utils_test.ts
- test/swap_test.ts
- test/utils/mocks.ts
> feat: Add support for buy token affiliate fees

- src/token_metadatas_for_networks.ts
Adds new stablecoins (bUSD, mUSD, and PAX) to token registry
> feat: Adds bUSD, mUSD, and PAX to token registry

- package.json
- src/handlers/swap_handlers.ts
- src/token_metadatas_for_networks.ts
- src/utils/market_depth_utils.ts
- test/market_depth_test.ts
- yarn.lock
* Prevent ETH/WETH depth requests
* Handle depth by address requests
> fix: handle addresses in depth

- package.json
- test/rfqt_test.ts
- yarn.lock
Adds new asset swapper with `keep-alive`
> fix: added new asset swapper

- src/ormconfig.ts
> fix: lower db pool connections

- test/swap_test.ts
- test/swap_v0_test.ts
> fix: excluded sources test

- src/config.ts
- src/services/swap_service.ts
* Updates the fee schedule for the latest EP
* Uses gross gas for just the source and adds in the base cost later. So the path optimizer doesn't pay the full hit of overhead.
* Removes the buffer if the sources are more deterministic
> feat: update fee schedule for v1

- package.json
- yarn.lock
> fix: Update package.json

- src/handlers/staking_handlers.ts
- src/services/staking_data_service.ts
> fix: move staking queries to sequential

- package.json
- src/config.ts
- src/utils/parse_utils.ts
- test/utils/mocks.ts
- yarn.lock
* Adds support for Mooniswap
https://github.com/0xProject/0x-monorepo/pull/2675
> feat: added mooniswap

- package.json
- src/config.ts
- yarn.lock
USDT transfer return decode bug :(
> fix: mooniswap usdt

- package.json
- src/rpc_subprovider.ts
- src/utils/provider_utils.ts
Requests compressed RPC responses
> feat: Compressed RPC responses

- docker-compose.yml
- package.json
- src/config.ts
- src/handlers/swap_handlers.ts
- src/services/swap_service.ts
- src/types.ts
- src/utils/parse_utils.ts
- src/utils/service_utils.ts
- test/utils/mocks.ts
- yarn.lock
> feat: Add support for bunny hop

- package.json
- src/handlers/swap_handlers.ts
- yarn.lock
https://github.com/0xProject/0x-monorepo/pull/2685
> chore: redeploy bunny hop

- package.json
- src/config.ts
- yarn.lock
* Splits over Kyber reserves
* Reduces gas cost for Kyber
https://github.com/0xProject/0x-monorepo/pull/2683
> feat: Better Kyber quotes

- src/apm.ts
- src/app.ts
- src/config.ts
- test/rfqt_test.ts
> chore: more apm profiling

- docker-compose.yml
- package.json
- yarn.lock
> feat: champagne problems EP migration

- package.json
- src/config.ts
- src/token_metadatas_for_networks.ts
- src/utils/parse_utils.ts
- test/utils/mocks.ts
- yarn.lock
https://github.com/0xProject/0x-monorepo/pull/2698
> feat: SushiSwap and Swerve

- src/token_metadatas_for_networks.ts
> chore: Add UNI to token metadata

- package.json
- src/config.ts
- src/handlers/meta_transaction_handlers.ts
- src/handlers/swap_handlers.ts
- src/types.ts
- yarn.lock
Enable Bancor as a source, but only for requests with BNT.
> Enable bancor for requests with BNT

- src/handlers/meta_transaction_handlers.ts
> fix: metatx potentially undefined excluded sources if not provided

- package.json
- src/config.ts
- src/handlers/meta_transaction_handlers.ts
- src/handlers/swap_handlers.ts
- src/services/swap_service.ts
- src/types.ts
- src/utils/parse_utils.ts
- test/parse_utils_test.ts
- test/swap_test.ts
- yarn.lock
Also add `includedSources` query param support to end points. I hate how much work this totally uncalled for feature took. :weary: 
> feat: add uniswap VIP support

- package.json
- src/config.ts
- yarn.lock
> feat: Add Curve tripool

- package.json
- src/config.ts
- src/services/swap_service.ts
- src/utils/parse_utils.ts
- src/utils/service_utils.ts
- test/meta_transaction_test.ts
- test/service_utils_test.ts
- test/swap_test.ts
- yarn.lock
- Fix balancer sampling bug causing reverts on-chain in AS.
- Fix min buy amount calculations allowing extreme slippage in AS.
- Fix sushiswap gas schedule for uniswap VIP.
- Fix LP and MB sources leaking into `getBuy/SellQuotes()` operations in AS.
- Fix `includedSources` param not being properly parsed.
- Allow `excludedSources` to include `Mesh` to exclude open-orderbook.
> fix: Balancer, min buy amounts, gas schedule

- src/handlers/swap_handlers.ts
- src/routers/swap_router.ts
- src/services/swap_service.ts
Adds v1 support for `/tokens` and `/prices`
> fix: Add /prices and /tokens mirrors to v1 endpoints

- .github/workflows/deploy.yml
> [v0] update workflows

- package.json
- src/config.ts
- src/constants.ts
- src/services/swap_service.ts
- src/utils/signer.ts
- test/price_comparison_utils_test.ts
- yarn.lock
> feat: Add EP overhead function to V1 opts

- package.json
- src/config.ts
- test/utils/mocks.ts
- yarn.lock
> feat: Shell 🐚

- package.json
- yarn.lock
https://github.com/0xProject/0x-monorepo/pull/2723
> fix: gas incorrectly scaled by gas price

- src/utils/service_utils.ts
- test/service_utils_test.ts
- test/swap_test.ts
> fix: Returned `buyAmount` not matching queried `buyAmount`

- package.json
- yarn.lock
https://github.com/0xProject/0x-monorepo/pull/2724
> fix: overflow in depth buys

- .github/workflows/deploy.yml
Complements https://github.com/0xProject/0x-main-infra/pull/723
> Update deploy script to skip v0 when deploying

- src/queries/staking_queries.ts
Fix individual staking pool query.
> fix: fixed indiviudal pool avg rewards query

- src/queries/staking_queries.ts
> fix: swap_v0 2020-10-10 fixes

- package.json
- src/config.ts
- test/utils/mocks.ts
- yarn.lock
> feat: DODO

- src/handlers/swap_handlers.ts
- src/services/meta_transaction_service.ts
- src/utils/quote_report_utils.ts
Add {buy,sell}Amount and {buy,sell}tokenAddress to quote report log line
> chore: Add additional metadata to QuoteReport log line

- src/config.ts
Disables MultiBridge. Not being actively used and is causing a few issues with some unique tokens (like Uniswap LP tokens)
> chore: Disable MultiBridge on Mainnet

- src/config.ts
Disabled multibridge on mainnet for the v0 branch.
> fix: Disabled multibridge on mainnet

- package.json
- src/config.ts
- test/meta_transaction_test.ts
- test/swap_test.ts
- yarn.lock
https://github.com/0xProject/0x-monorepo/pull/2730
> fix: includedSources and MultiBridge edgecases

- package.json
- src/config.ts
- src/token_metadatas_for_networks.ts
- src/utils/market_depth_utils.ts
- test/utils/mocks.ts
- yarn.lock
- Adding SnowSwap as a liquidity source
- 0x-monorepo PR: https://github.com/0xProject/0x-monorepo/pull/2729 
> feat: SnowSwap

- package.json
- test/rfqt_test.ts
- yarn.lock
Simply upgrades asset swapper to the latest version `v4.7.0`
> feat: upgrades Asset Swapper

- src/utils/quote_report_utils.ts
Excludes the `fillData` field for Quote Report
> fix: removes fillData from quote report

- package.json
- src/app.ts
- src/config.ts
- src/services/swap_service.ts
- src/utils/price_comparison_utils.ts
- yarn.lock
[Sims](https://metabase.spaceship.0x.org/dashboard/139?run_id=employ-hesitant-weight&adjusted_amount_bought_win_tolerance__bps_=0.5)
> feat: Refactored Asset-swapper addresses and gas schedule

- src/handlers/swap_handlers.ts
> fix: return WETH depth chart data for when ETH is requested

- package.json
- src/config.ts
- yarn.lock
- protocol PR: https://github.com/0xProject/protocol/pull/14
> fix: fixing kovan by disabling all sources except UniswapV2

- package.json
- yarn.lock
[Sims v prod, rolled up](https://metabase.spaceship.0x.org/dashboard/139?run_id=practice-fumbling-fireman&adjusted_amount_bought_win_tolerance__bps_=0.5)
Updates AS to support multiple Shell pools
> fix: Support multiple Shell pools

- src/handlers/meta_transaction_handlers.ts
- src/types.ts
> fix: affiliate address param not being passed for mtx v1 swaps

- src/token_metadatas_for_networks.ts
> fix: Aave to token registry

- src/handlers/meta_transaction_handlers.ts
We only use the symbol to see if it is `ETH` 
> fix: meta txn arbitrary tokens

- package.json
- yarn.lock
> feat: New FQT

- package.json
- yarn.lock
> feat: asset-swapper bump (including Curve metapools)

- migrations/1605637330716-CreateMakerBalanceChainCache.ts
- src/entities/MakerBalanceChainCacheEntity.ts
Added an entity to cache RFQT maker balances to the DB for off-chain order validation in the future.
> feat: Added maker balance cache to 0x API db

- package.json
- src/handlers/swap_handlers.ts
- src/services/swap_service.ts
- test/meta_transaction_test.ts
- test/price_comparison_utils_test.ts
- test/utils/mocks.ts
- yarn.lock
Updates to latest AS which returns the decimals from the sampler and has an updated gas schedule.
[Sim](https://metabase.spaceship.0x.org/dashboard/139?run_id=deserve-warlike-ink&adjusted_amount_bought_win_tolerance__bps_=0.5)
> feat: Update AS to latest gas schedule + decimals from sampler

- package.json
- yarn.lock
Deploying new asset-swapper package that has an improved comparison price function for RFQT market makers.
See https://github.com/0xProject/protocol/pull/32.
> feat: Improved comparison price function for RFQT market makers

- package.json
- yarn.lock
https://github.com/0xProject/protocol/pull/41
[Sims](https://metabase.spaceship.0x.org/dashboard/139?run_id=arbitrate-skinny-driving&adjusted_amount_bought_win_tolerance__bps_=0.5)
> fix: disable balancer/cream off-chain sampling

- .github/workflows/deploy.yml
- .github/workflows/release.yml
> chore: upgrade to use create-pull-request v3 due to v2 not supported

- src/config.ts
- src/services/swap_service.ts
- src/utils/gas_station_utils.ts
- test/rfqt_test.ts
- test/swap_test.ts
-   [x] Test changes on the staging environment with [Matcha API Staging](https://api-staging.matcha.xyz).
-   [x] Swap endpoints
-   [x] Meta transaction endpoints
> feat: pad protocol fee estimate for quotes that include RFQT orders

- package.json
- src/services/order_watcher_service.ts
- src/services/orderbook_service.ts
- src/types.ts
- src/utils/mesh_utils.ts
- test/orderbook_service_test.ts
- yarn.lock
Fixes a bug in parsing mesh order events and rejection codes. Previously would occasionally return an undefined order state, which results in an uncaught error when saving to the database. 
Also includes a bit of a refactor. Trying to make the order watcher service more readable.
For more information see `0x API Matcha smoke test runbook` in …
> fix: handling mesh order event end state

- src/runners/rfq_maker_balance_cache_runner.ts
Started an instance of `MetricsService` to fix Prometheus metrics collection for the Balance Cache Service.
> fix: added metrics service to balance cache runner

- docker-compose.yml
- package.json
- yarn.lock
> feat: hot-pants migration

- .gitignore
- src/handlers/swap_handlers.ts
- src/services/meta_transaction_service.ts
- src/services/swap_service.ts
- src/types.ts
For contracts where the balance is non-deterministic we want to sell what is available. 
Requires: https://github.com/0xProject/protocol/pull/37
> feat: Support selling entire balance

- package.json
- src/handlers/swap_handlers.ts
- src/services/swap_service.ts
- yarn.lock
https://github.com/0xProject/protocol/pull/88
TODO
> fix: Bancor enabled always

- src/services/swap_service.ts
> fix: Make the gas price adjustment for RFQT fast +20%

- migrations/1608130412812-AddCreatedAtToSignedOrders.ts
- package.json
- yarn.lock
> feat: created at to signed orders migration, 0x/contract-addresses bump

- package.json
- yarn.lock
https://github.com/0xProject/protocol/pull/98 
> fix: CryptoCom

- package.json
- src/token_metadatas_for_networks.ts
- yarn.lock
https://github.com/0xProject/protocol/pull/100
> feat: Mooniswap V2

- package.json
- yarn.lock
https://github.com/0xProject/protocol/pull/106
> fix: Buy fillAmount when shouldSellEntireBalance is set

- package.json
- yarn.lock
- https://github.com/0xProject/protocol/pull/103: feat: adding UST, BBTC, OBTC, aDAI, aUSDC, aUSDT, sEUR, EURS, sETH pools #103
- https://github.com/0xProject/protocol/pull/102: chore: [asset-swapper] Update Shells to new version #102 
> feat: AssetSwapper 5.6.2: new Curve Pools and new Shell version

- package.json
- yarn.lock
Batched some suggested dependency updates and security fixes to easier test them.
> chore: Security updates to dependencies

- src/middleware/cache_control.ts
- src/runners/http_service_runner.ts
- src/runners/http_sra_service_runner.ts
- src/runners/http_staking_service_runner.ts
- src/runners/http_swap_service_runner.ts
Default all GET request to have a cache control of 10s.
> chore: cache control default

- package.json
- yarn.lock
https://github.com/0xProject/protocol/pull/111
> feat: Kyber reserves and Mooni 2.1

- src/runners/order_watcher_service_runner.ts
> chore: add prometheus monitoring to order watcher

- package.json
- yarn.lock
> fix: Try mesh-graphql-client without result caching

- .gitignore
- src/constants.ts
- src/runners/rfq_maker_balance_cache_runner.ts
- test/rfq_maker_balance_cache_test.ts
Altered RFQ balance cache scraping to use a function that takes allowance into account.
Update tests to check that allowance functionality is working.
> feat: update balance cache runner to take allowance into account

- package.json
- src/services/swap_service.ts
- yarn.lock
> fix: Multihop second source missing + pad gas

- .github/workflows/deploy.yml
- package.json
- src/app.ts
- src/config.ts
- yarn.lock
> fix: RFQOrder fee schedule

- src/middleware/cache_control.ts
- src/runners/http_sra_service_runner.ts
- src/runners/http_staking_service_runner.ts
- src/runners/http_swap_service_runner.ts
```
curl -vvv 'http://localhost:3001/swap/v1/quote?buyToken=USDC&sellToken=DAI&sellAmount=1000000000000000000000'
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 3001 (#0)
> GET /swap/v1/quote?buyToken=USDC&sellToken=DAI&sellAmount=1000000000000000000000 HTTP/1.1
> Host: localhost:3001
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Cache-control: public, max-age=10, s-maxage=10
< Access-Control-Allow-Origin: *
< Content-Type: application/json; charset=utf-8
< Content-Length: 2383
< ETag: W/"94f-Z3GVZi+vQBBB5wfrr7mTSbuc144"
< Date: Fri, 19 Feb 2021 11:58:15 GMT
< Connection: keep-alive
< Keep-Alive: timeout=76
```
-   [ ] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. …
> feat: cache control header

- src/services/order_watcher_service.ts
- src/services/websocket_service.ts
> fix: re-setup GQL subscriptions after reconnecting to Mesh v10

- package.json
- yarn.lock
> fix: Disable Aave Curves

- docker-compose.yml
- package.json
- yarn.lock
> chore: bump Mesh versions

- src/handlers/swap_handlers.ts
If query includes slippagePercentage=0; we should use 0 instead of the default 0.001.
Thanks javascript:
```
[14:30:00]0x-api (fix/default-slippage)$ node
Welcome to Node.js v12.19.0.
Type ".help" for more information.
> 0 || 0.1
0.1
```
> stop treating 0 as undefined

- src/services/orderbook_service.ts
- test/sra_test.ts
> fix: SRA trader query param should AND match with order filter props

- package.json
- src/config.ts
- yarn.lock
Integrate a new version of asset-swapper that has a tx origin blacklist option for RFQT.
> feat: integrate tx origin blacklist, fix config typos

- src/config.ts
> fix: ref to alt mm env vars in empty env var check

- package.json
- src/config.ts
- src/services/meta_transaction_service.ts
- src/services/swap_service.ts
- test/constants.ts
- test/utils/mesh_test_utils.ts
- yarn.lock
Updates AS version and EP gas overhead functions for Multiplex. 
https://github.com/0xProject/protocol/pull/168
> feat: Multiplex integration

- package.json
- yarn.lock
https://github.com/0xProject/protocol/pull/178
> fix: Multiplex PLP multihop encoding issue

- package.json
- yarn.lock
The latest version of Asset Swapper adds a cancel token to RFQ requests. This change is simply a version bump of Asset Swapper
> feat: add cancelToken to RFQ requests

- package.json
- src/config.ts
- src/handlers/swap_handlers.ts
- src/services/postgres_rfqt_firm_quote_validator.ts
- src/services/swap_service.ts
- src/types.ts
- src/utils/alt_mm_utils.ts
- test/rfqt_test.ts
- yarn.lock
Upgrade asset swapper version and fix all the types that had name changes
> chore: rename types from {Rfqt=>Rfq}

- package.json
- yarn.lock
Bump asset-swapper to improve logging of alt RFQT requests/responses.
> feat: bump AS package to improve alt RFQ logging

- src/runners/rfq_maker_balance_cache_runner.ts
> feat: added tolerance for web3 and DB errors, improved logging for balance cache worker

- docker-compose-test.yml
- docker-compose.yml
- package.json
- src/app.ts
- src/config.ts
- src/errors.ts
- src/handlers/meta_transaction_handlers.ts
- src/handlers/swap_handlers.ts
- src/rpc_subprovider.ts
- src/services/swap_service.ts
- src/token_metadatas_for_networks.ts
- src/types.ts
- src/utils/price_comparison_utils.ts
- src/utils/service_utils.ts
- src/utils/token_metadata_utils.ts
- test/docker-compose-test.yml
- test/docker-compose.yml
- test/swap_test.ts
- tsconfig.json
- yarn.lock
> feat: BSC [TKR-23]

- src/middleware/error_handling.ts
- src/services/websocket_service.ts
> fix error handling

- package.json
- yarn.lock
Upgrades Asset Swapper package
> fix: optional last look parameter

- src/config.ts
- src/handlers/swap_handlers.ts
Validation ensures that the quote provided will be valid for the provided taker.
There is a param that allows a swap quote request to skip validation checks. These changes set this to false always for Matcha.
> feat: don't allow matcha to skip validation of firm quotes

- src/runners/rfq_maker_balance_cache_runner.ts
- src/services/postgres_rfqt_firm_quote_validator.ts
- test/quote_validator_test.ts
We are experiencing a high cache miss rate due to case sensitivity. The fix here is to compare everything in terms of lower case.
Integration test added on the validator side.
> fix: cache misses due to case sensitivity [BUG - do not merge] 

- package.json
- src/handlers/swap_handlers.ts
- src/logger.ts
- src/middleware/error_handling.ts
- src/utils/quote_report_utils.ts
- yarn.lock
https://github.com/0xProject/api-utils/pull/2
> feat: enable logging with request id

- src/handlers/swap_handlers.ts
- src/services/meta_transaction_service.ts
- src/utils/quote_report_utils.ts
Add API key to firm quote report logs.
> feat: add API key to quote report logs

- src/config.ts
This is the commit that implements the recommendation of our most recent findings that reducing the gas schedule for multiplex batch fill orders will improve pricing for users.
> chore: tweak gas schedule for native orders down by 10K

- package.json
- yarn.lock
> chore: bump AS for PancakeSwapV2

- src/services/swap_service.ts
> fix: Use ASSET_SWAPPER_MARKET_ORDERS_OPTS_NO_VIP if shouldSellEntireBalance [TKR-87]

- Dockerfile
- package.json
- src/rpc_subprovider.ts
- yarn.lock
https://github.com/0xProject/protocol/pull/183
[TKR-24]
> feat: pruned paths + fast abi

- package.json
- yarn.lock
> fix: BSC pancake VIP

- package.json
- yarn.lock
> fix: Temporarily remove PancakeV2/Bakery from VIP

- package.json
- src/services/swap_service.ts
- yarn.lock
> feat: UniswapV3 BalancerV2

- .github/workflows/deploy.yml
> fix: Github deploy action from branch instead of master [TKR-98]

- src/services/rfqm_service.ts
- src/utils/quote_comparison_utils.ts
- test/utils/quote_comparison_utils_test.ts
Refactors the logic for getting the best quote such that one code path will work for both firm and indicative quotes. This makes the code easier to read and maintain in the future.
Comes with unit tests.
> refactor: introduce getBestQuote

- test/sra_test.ts
When EGS was down, had to comment out these tests. They're back, so these tests are passing again
> chore: bring back sra tests

- package.json
- src/services/swap_service.ts
- test/swap_test.ts
- yarn.lock
When EGS was down, had to comment out these tests. EGS is back... but tests are currently failing. Starting this diff and hoping someone can help me fix the tests... or the code in case a bug slipped past us
> chore: bring back swap tests

- package.json
- yarn.lock
https://github.com/0xProject/protocol/pull/233
> fix: Two hop sampler

- README.md
- package.json
Add a command for generating migrations.
> build: add a command for generating migrations

- package.json
- src/config.ts
- src/services/rfqm_service.ts
- test/rfqm_test.ts
- yarn.lock
> fix: add Ropsten supported sources [TKR-93]

- README.md
> fix: readme formatting messed up

- src/constants.ts
- src/services/rfqm_service.ts
- test/rfqm_test.ts
- test/services/rfqm_service_test.ts
Passing a real fee into Quote Requestor.
Unit and integration tests updated
> fix: pass fee into QuoteRequestor

- src/constants.ts
> fix: Update constants.ts

- package.json
- yarn.lock
> feat: bump mesh graphql client to 11.2

- src/utils/rfqm_worker_balance_utils.ts
- test/utils/rfqm_worker_test.ts
> feat: Rfq healtcheck worker #2!

- src/utils/rfq_blockchain_utils.ts
- test/rfq_blockchain_utils_test.ts
Add a method to validate MTX calldata instead of an mtx object.
> feat: add method on rfqBlockchainUtils to validate calldata

- package.json
- yarn.lock
Upgrades Token Metadata to include Ropsten dummy tokens
> fix: upgrades Token Metadata

- src/runners/http_rfqm_service_runner.ts
Fixes a small bug in SQS initialization
> fix: small typo in SQS initialization

- src/utils/rfqm_db_utils.ts
- test/rfqm_db_test.ts
> feat: add update and find methods for RfqmJob

- package.json
- yarn.lock
> fix: 0x/token-metadata bump

- .github/workflows/deploy.yml
> fix: syntax issue in github deploy action

- src/runners/http_rfqm_service_runner.ts
- src/utils/rfq_blockchain_utils.ts
- test/rfq_blockchain_utils_test.ts
> feat: refactor rfq_blockchain_utils dependencies, add submit calldata function

- src/runners/rfqm_worker_runner.ts
> fix: express import for rfqm worker

- src/config.ts
- src/runners/http_rfqm_service_runner.ts
- src/runners/rfqm_worker_runner.ts
- src/utils/provider_utils.ts
- src/utils/rfq_blockchain_utils.ts
> feat: make rfqm worker aware of its respective private key

- src/config.ts
Guess we aren't cheaper than uniswap after all :disappointed: . I blame Berlin.
> feat: Tweak uni3 vip overhead

- src/services/rfqm_service.ts
- test/rfqm_test.ts
plug transaction submission into job processing.
> feat: add completeSubmissionLifecycleAsync to processRfqmJobAsync

- package.json
- src/services/rfqm_service.ts
- src/utils/quote_server_client.ts
- test/rfqm_test.ts
- test/utils/quote_server_client_test.ts
- yarn.lock
As discussed, we added [takerTokenFillAmount](https://github.com/0xProject/quote-server/pull/21) in the Submit request and response. I've updated the QuoteServerClient to reflect these changes.
> fix: Submit tx upgrade

- src/config.ts
- src/runners/http_rfqm_service_runner.ts
- src/runners/rfqm_worker_runner.ts
> fix: rename rfqm worker index var to RFQM_WORKER_INDEX

- src/utils/rfq_blockchain_utils.ts
> fix: swap out test provider with param

- src/utils/rfq_blockchain_utils.ts
> fix: keep provider as a param in constructor since it's not used elsewhere

- src/services/rfqm_service.ts
- src/utils/rfq_blockchain_utils.ts
- test/rfqm_test.ts
fixes:
- finalization logic for tx submission
- handling errors for getting tx receipts
adds:
- extra error logging to tx submission
> fix: fix finalization logic and tx receipt handling

- src/services/rfqm_service.ts
- src/utils/rfq_blockchain_utils.ts
> fix: await promise for receipt

- src/entities/RfqmJobEntity.ts
- src/entities/RfqmQuoteEntity.ts
- src/entities/RfqmTransactionSubmissionEntity.ts
- src/services/rfqm_service.ts
- src/utils/rfqm_db_utils.ts
- test/rfqm_db_test.ts
- test/rfqm_test.ts
- Beat at the TypeScript type checker until we have removed the `?` types in the RFQM entities where we known the column is non-nullable.
- Move types the entity depends on to the entity definition file. This removes the import cycle between entities and `rfqmDbUtils` and creates a clearer dependency path.
- Ensure that we are relying on the database's clock for default `createdAt` times
No underlying changes to the database happen due to this PR; everything here is at the TS type level.
- Ensure db comes up and migrates
- Ensure db test passes, paying attention to new time check
-   [ ] Add …
> fix: Align RFQM entity types with their db representations

- package.json
- yarn.lock
- Curve V2: (asset-swapper and contract-addresses bump)
> feat: Curve V2, asset-swapper and contract-addresses bump

- src/services/rfqm_service.ts
- test/services/rfqm_service_test.ts
Add logic to the rfqm service to handle the future /status endpoint.
TODO: write handler
Unit test suite included.
> feat: Add status logic to rfqm service

- src/handlers/rfqm_handlers.ts
- src/routers/rfqm_router.ts
- src/services/rfqm_service.ts
- test/rfqm_test.ts
- test/services/rfqm_service_test.ts
- Create the handler for the rfqm `/status/:orderHash` resource
- Add the route with the associated handler
- Add integration tests
Run the new integration tests
> feat: Create rfqm status handler and add to router

- test/rfqm_test.ts
Run these tests like 10 times and see if this stops the non-deterministic test failures. Will keep track of test runs in the comments
> fix: use a deterministic fake signature in test

- migrations/1623716682037-DropRfqmStatusReasonColumn.ts
- src/entities/RfqmJobEntity.ts
- src/services/rfqm_service.ts
- test/rfqm_db_test.ts
- test/rfqm_test.ts
- test/services/rfqm_service_test.ts
The `RfqmJobStatus` enum was `"in_queue" | "pending" | "succeeded" | "failed"` with a `statusReason` `string` field/column to add extra information.  Remove the `statusReason` and expand the `RfqmJobStatus` so that it details all cases. This will make it easier to handle the cases down the road (for instance, if a client wants to know if a market maker rejected last look and show an i18n-ized message).
Create db migration to drop unused column.
- Run updated tests
- Run db migration locally
-   [ ] Test changes on the staging environment with [Matcha …
> feat: Change the RfqmJobStatus to an exhaustive enum

- src/config.ts
> fix: re-enable Maker PSM

- src/entities/RfqmTransactionSubmissionEntity.ts
- src/services/rfqm_service.ts
- test/rfqm_db_test.ts
- test/rfqm_test.ts
- test/services/rfqm_service_test.ts
> feat: add Confirmed status to RfqmTransactionSubmission

- src/services/rfqm_service.ts
- test/services/rfqm_service_test.ts
> fix: fix status expiry check--expiry is in s (not ms)

- src/utils/rfq_blockchain_utils.ts
> fix: increase RFQM gas estimate buffer to 50%

- src/entities/RfqmJobEntity.ts
Note that this is `s` not `ms`
> fix: Add comment about expiry to RfqmJobEntity

- src/runners/rfqm_worker_runner.ts
- src/utils/sqs_consumer.ts
- test/utils/sqs_consumer_test.ts
> refactor: better error logging

- src/runners/rfqm_worker_runner.ts
When an unexpected error should suddenly happen, the worker process should exit, as opposed to fail silently
> fix: when errors are encountered, fail

- src/services/rfqm_service.ts
- test/services/rfqm_service_test.ts
> fix: don't re-submit unless gas price is > 10% higher than previous

- src/runners/http_rfqm_service_runner.ts
- src/services/rfqm_service.ts
- test/rfqm_test.ts
In order to make sure we never submit a job after the last look has been declined, we'll clear out the calldata.
> feat: clear out calldata after last look declined

- package.json
- src/utils/rate-limiters/base_db_limiter.ts
- src/utils/rate-limiters/base_limiter.ts
- yarn.lock
Update typescript version to latest
`yarn test` passes 4.0
> chore: Bump typescript

- src/utils/quote_server_client.ts
> fix: add a Content-Type header for submit endpoint requests

- src/utils/rfqm_health_check.ts
- test/utils/rfqm_health_check_test.ts
Creates checks which examine the SQS queue for a buildup of messages or for old messages which may be expired or expire soon.
TODO: Add the queue check to the health check
Tests with mocked queue responses are included.
> feat: Create RFQm queue checks

- package.json
- yarn.lock
> feat: Balancer V2 Polygon

- src/services/rfqm_service.ts
> fix: Added new metrics

- src/entities/RfqmWorkerHeartbeatEntity.ts
- src/utils/rfqm_health_check.ts
- test/utils/rfqm_health_check_test.ts
Add a function to the rfqm health check library to examine worker heartbeats and create appropriate issues.
Unit tests included!
> feat: Create function to find issues with RFQM worker heartbeats

- package.json
- yarn.lock
> chore: asset-swapper bump: PLP Polygon, KyberDMM all pools, Polygon KyberDMM

- package.json
- yarn.lock
> chore: PLP fallback + Polygon MultiHop

- src/utils/rfqm_health_check.ts
- test/utils/rfqm_health_check_test.ts
Create the http checker for the RFQm health check logic. "http" is a bit of a misnomer; these are top-level-ish system checks that don't involve the worker farm. The checks:
- raise a MAINTENANCE issue when the related env var is set
- raise a FAILED issue when the registry balance is below the threshold
Unit test it!
For more information see …
> feat: Create http issues function for the rfqm health check

- src/services/rfqm_service.ts
The service has the registry address as a property, but one function used the unwrapped (ugh) config value.
Closes MKR-121
> fix: rfqm_service.ts -- change method to use registry address property

- package.json
- yarn.lock
> chore: AS bump, ShibaSwap

- src/handlers/rfqm_handlers.ts
- src/services/rfqm_service.ts
- src/utils/rfqm_db_utils.ts
- src/utils/rfqm_health_check.ts
- test/rfqm_test.ts
- test/services/rfqm_service_test.ts
Here's the big one. Takes all the pieces of the RFQm health check built over the past weeks and combines them. In the handler, the result of the health check is cached to save computation resources. The user can override the caching with a `Cache-Control` header in the request.
Closes MKR-48
Since all the individual pieces of the health check are tested, I elected to test this PR manually. With a local dev server attached to the debugger I verified the caching features and sanity checked that the `computeHealthCheckAsync` method was being called as expected.
-   [ ] Add tests to cover changes as …
> feat: Create full RFQm health check implementation

- src/services/rfqm_service.ts
> chore: add metric for process job latency

- package.json
- yarn.lock
> feat: AS bump: JetSwap

- src/services/rfqm_service.ts
> chore: add logging when RFQM error is caught

- src/entities/RfqmTransactionSubmissionEntity.ts
- test/rfqm_db_test.ts
> fix: allow nonce 0 to be written to DB

- src/config.ts
- test/parse_utils_test.ts
Migration has been completed to `API_KEYS_ACL`. Remove fallback logic.
> feat: Remove legacy rfq acl config

- package.json
- yarn.lock
> feat: IronFinance, Saddle: alETH, D4 pools

- src/handlers/rfqm_handlers.ts
- src/handlers/swap_handlers.ts
- src/services/rfqm_service.ts
- src/services/swap_service.ts
- src/types.ts
- src/utils/config_manager.ts
- test/rfqm_test.ts
- test/services/rfqm_service_test.ts
Modifies 0x API to use the integrator ID for transaction logs and to send to market makers.
> feat: Use integrator ID for logs and to send to market makers

- package.json
- yarn.lock
> feat: AS bump: ACryptoS

- src/handlers/swap_handlers.ts
- unknown integrators like simbot couldn't use skipValidation=true anymore 
> fix: allow unknown integrators to set skipValidation

- package.json
- yarn.lock
> fix: fill amounts rounding error

- src/services/rfqm_service.ts
Nothing wrong per se, but cleaning a little.
> refactor: clean up rfqm service

- src/services/rfqm_service.ts
Add logging around transaction submission. Make sure to grab the transaction hash
> chore: add better logging around transaction submission

- package.json
- yarn.lock
Pin to 0.27.0 to avoid multiplex encoding incompatibility 
> fix: pin to contract-zero-ex 0.27.0

- src/runners/http_rfqm_service_runner.ts
- src/runners/rfqm_worker_runner.ts
- src/services/swap_service.ts
- src/utils/metrics_service.ts
Adds more metrics to 0x API for RFQM and RFQT
> fix: Added metrics proxy

- src/utils/rfqm_db_utils.ts
- test/utils/rfqm_db_utils_test.ts
There's a bug in how we map to RfqOrder from StoredOrder
> fix: incorrect mapping from stored order

- package.json
- src/constants.ts
- yarn.lock
* Native partial fill
* Retire Eth2Dai/Oasis
> feat: Native partial fill

- src/constants.ts
- src/routers/orderbook_router.ts
- src/runners/http_service_runner.ts
- src/runners/http_sra_service_runner.ts
> feat: add orderbook routing

- src/services/websocket_service.ts
> chore: use randomHex for the random component in kafka group id

- package.json
- yarn.lock
> chore: AS bump

- .github/workflows/deploy.yml
- integration-test/transaction_watcher_service_test.ts
- package.json
- src/app.ts
- src/config.ts
- src/handlers/meta_transaction_handlers.ts
- src/services/swap_service.ts
- src/types.ts
- src/utils/price_comparison_utils.ts
- src/utils/rfq_blockchain_utils.ts
- test/price_comparison_utils_test.ts
- test/rfq_blockchain_utils_test.ts
- yarn.lock
> feat: Avalanche

- package.json
- src/config.ts
- src/schemas/integrator_acl_schema.json
- src/services/rfqm_service.ts
- src/services/swap_service.ts
- test/config_test.ts
- test/test_env
- yarn.lock
Adds new support for API keys that target 1 or more specific maker URIs. This allows market makers to test their implementations easily
> fix: Added new API keys for custom integrations

- package.json
- src/config.ts
- src/handlers/rfqm_handlers.ts
- src/handlers/swap_handlers.ts
- src/services/rfqm_service.ts
- src/services/swap_service.ts
- src/types.ts
- src/utils/config_manager.ts
- src/utils/metrics_service.ts
- test/config_test.ts
- test/rfqm_test.ts
- test/services/rfqm_service_test.ts
- yarn.lock
Adds RFQ metrics and fixes the Asset Swapper issues with API key <> Integration key
> fix: Added RFQ changes for 0x API

- src/utils/rfqm_worker_balance_utils.ts
- test/utils/rfqm_worker_test.ts
- Remove functions exported just for testing
- Slightly flatten the call stack
- Add a test for outstanding transactions
> refactor: Refactor and upgrade tests for rfqm_worker_balance_utils

- src/utils/metrics_service.ts
Reduces the combinatorial complexity of Prometheus tags (that will reduce the number of tags created, therefore will also reduce the load)
> fix: Add better market metrics

- src/app.ts
- src/config.ts
Adds configurable wsPath for the WebsocketService.
> feat: support custom ws path

- src/runners/http_service_runner.ts
This PR adds the `WebsocketService` to the default `http_service_runner`.
> chore: add optional Websocket service to root http_service_runner

- src/config.ts
- src/constants.ts
Set `PROTOCOL_FEE_MULTIPLIER` equal to zero in order to remove protocol fees.
-   [ x] Prefix PR title with `[WIP]` if necessary.
> feat: remove protocol fees WIP

- .github/workflows/deploy.yml
> fix: add polygon staging to deploy action

- src/services/rfqm_service.ts
Errors on retry are crashing the worker and not being logged. Log them and clean up some logic.
> feat: Log rfqm retry failures

- package.json
- yarn.lock
> chore: bump AS to 16.29.1

- src/runners/rfqm_worker_runner.ts
My informed suspicion is that the RFQM worker processes are encountering unhandled errors and exiting. Currently, there is a log statement before the exit, but no logs exists for this callsite. There is a special log function provided by the `pino` library which blocks the exit until the log has been written.
Update the RFQM worker routine to use the blocking log function before exiting the process. …
> fix: Fix logging for rfqm worker exit

- src/utils/rfqm_health_check.ts
- Change the logic of the RFQM system health gauge such that it will go back to operational when the issue is resolved.
- Update the name of the gauge to prevent conflicts with old data.
> fix: Update status guage so it resets when the issue is resolved

- src/runners/rfqm_worker_runner.ts
- src/services/rfqm_service.ts
- src/utils/sqs_consumer.ts
We're missing logs from the RFQM worker. @phil-ociraptor thinks this is caused by the log payload being too large for ES to handle.
Update the RFQM code to remove the full error.
> fix: Remove full error message from RFQM worker logging

- .github/workflows/deploy.yml
> feat: update deploy.yml for fantom deployment

- package.json
- yarn.lock
> feat: Uniswap V3 1bps pools

- package.json
- src/services/swap_service.ts
- src/utils/sampler_metrics.ts
- yarn.lock
See https://github.com/0xProject/protocol/pull/374
> chore: Add ability to capture sampler metrics

- src/utils/sampler_metrics.ts
Fix the name, meant to have `sampler_block_number`
> chore: Fix name for block number

- package.json
- yarn.lock
> fix: added new packages for celo deployment

- package.json
- yarn.lock
> feat: UniswapV3 on Polygon

- Dockerfile
- package.json
- src/rpc_subprovider.ts
> feat: node 16

- package.json
- src/utils/sampler_metrics.ts
- yarn.lock
> feat: push router performance metrics to prometheus

- .github/workflows/deploy.yml
- package.json
- yarn.lock
> fix: Celo optics v2 intermediate tokens

- Dockerfile
- package.json
- src/config.ts
- src/index.ts
- src/rpc_subprovider.ts
- src/runners/http_meta_transaction_service_runner.ts
- src/runners/http_rfqm_service_runner.ts
- src/runners/http_service_runner.ts
- src/runners/http_sra_service_runner.ts
- src/runners/http_swap_service_runner.ts
- src/runners/rfq_maker_balance_cache_runner.ts
- src/types.ts
- src/utils/provider_utils.ts
Use the following flag to enable `gzip` compressed requests. By default this is set to `false`. This requires special server support to handle compressed requests.
```
ENABLE_RPC_REQUEST_COMPRESSION=true
```
> feat: compressed requests

- package.json
> chore: stop running rfqm tests in this repo

- package.json
- yarn.lock
> chore: Curve ETH/CVX

- package.json
- src/config.ts
- yarn.lock
> fix: bump asset swapper and use equispaced samples for rust router

- src/handlers/swap_handlers.ts
Remove the line of code that logs out info about an InternalServerError. This log is not necessary as we already re-throw the error and information about the error (and stack trace) will be printed out by the errorHandler middleware here: https://github.com/0xProject/api-utils/blob/69dd016bc3e1a97b27b2a19936603334c71562c3/src/middleware/error_handler.ts#L107
- Checkout `master`. Provide an invalid RPC URL to `.env`. Build and run locally with `NODE_ENV=production yarn start:service:swap_http`
- Go to http://localhost:3000/swap/v1/quote?buyToken=DAI&sellToken=ETH&sellAmount=300000000000000000000
- The app will print out 3 lines of logs with 2 duplicated logs about the error (one at info level which was printed by line I'm removing, one at error level which is from api-utils).
- Now, …
> fix: remove unnecessary logs

- src/app.ts
- src/config.ts
- src/constants.ts
- src/entities/RfqMakerPairs.ts
- src/entities/RfqMakerPairsUpdateTimeHash.ts
- src/entities/index.ts
- src/schemas/index.ts
- src/schemas/rfq_maker_config.json
- src/schemas/rfq_maker_config_list.json
- src/services/swap_service.ts
- src/utils/config_manager.ts
- src/utils/pairs_manager.ts
- src/utils/rfq_maker_db_utils.ts
We are break the pair automation code changes into 5 different PRs:
1. Add makerId and apiKeyHashes fields for each maker in config files in infra repo.
2. Add DB table migration scripts and manually run them to create and populate table `rfq_maker_pairs`. It should be run after 1 is checked in.
3. Add maker API code to read/write from DB with tests in `0x-rfq-api` repo.
4. Add pair manager refresh code to utilize pairs information in DB for RFQm, in `0x-rfq-api` repo.
5. **(This PR)** Add pair manager refresh code to utilize pairs information in DB for RFQt, in `0x-api` repo.
-   [ ] Add tests …
> feat: refresh RFQt maker pairs from DB

- migrations/1638230050100-CreateRfqMakerPairsTable.ts
- migrations/1639527388617-PopulateRfqMakerPairsTable.ts
- migrations/1641933207280-CreateRfqMakerPairsUpdateTimeHashView.ts
- src/utils/pair_utils.ts
> feat: add migration scripts for maker API

- package.json
- src/handlers/swap_handlers.ts
- src/services/meta_transaction_service.ts
- src/services/swap_service.ts
- src/types.ts
- yarn.lock
Uses the fee sources (note: we sell and buy 0.1 ETH to UniswapV2|V3|SushiSwap and take the median) data to estimate if there is a large price impact from the quoted price.
This data is not perfect as it is not exhaustive (we don't check EVERY liquidity source) and does have some problems (median value could be worse than the routed value). It **may** prevent someone from absolutely getting nuked if we can detect it.
-   [ …
> chore: Estimate the price impact from fee source data

- src/services/postgres_rfqt_firm_quote_validator.ts
Cached maker balance use lower case maker address as key, while when querying the balance at runtime we use non-lower-case maker addresses, which result in a miss.
In that case, the maker address and token should be added to DB for monitoring. However, the lower case maker address is tried to be added to DB, which result in conflict and no ops. But a `NEW_ADDRESSES_SEEN` counter always increase:
- …
> fix: firm quote validator failed to read maker balance from DB

- package.json
- test/utils/mocks.ts
- yarn.lock
> chore: update asset-swapper

- package.json
- yarn.lock
* Deploys 0xProject/protocol#425
> chore: bump `asset-swapper` to include the latest neon-router changes

- package.json
- yarn.lock
https://github.com/0xProject/protocol/pull/441
> fix: Ropsten and UniswapV3

- package.json
- yarn.lock
Deploys
* 0xProject/protocol#439
* 0xProject/protocol#440
> feat: VIP routing & all sources in one call & optimize asset-swapper

- src/config.ts
> chore: Disable KyberDMM

- package.json
- src/config.ts
- yarn.lock
> feat: add EP overhead for RFQT vip

- package.json
- yarn.lock
> fix: RFQT VIP not respecting transformERC20 req

- package.json
- src/handlers/swap_handlers.ts
- src/services/meta_transaction_service.ts
- src/utils/quote_report_utils.ts
- yarn.lock
> feat: Add estimatedGas to quote report

- src/handlers/swap_handlers.ts
- src/utils/quote_report_utils.ts
This PR adds `decodedUniqueId` field to the Kafka quote report, making it easier to correlate two quote reports (e.g. /swap quote report and RFQm quote report). The `timestamp` field of the quote report is also modified to be consistent with how we generate `decodedUniqueId`.
> feat: add decodedUniqueId to quote report

- src/config.ts
* KyberDmm is also removed from Fantom exlcuded sources (no-op).
> feat: Enable KyberDmm on Avalanche [TKR-412]

- package.json
- yarn.lock
> chore: Remove 0x/migrations dev dependency

- src/config.ts
Polygon [`BridgeAdapter`](https://polygonscan.com/address/0x2d3f9173e29ff0558f2ed216e0ea4b81a91f191f#code) already supports KyberDMM. No contract deployment is needed to support this change.
> feat: Enable KyberDmm on Polygon [TKR-411]

- src/handlers/swap_handlers.ts
- src/types.ts
Add additional logging to see more information about the origin and affiliate address
> feat: log additional information regarding the request origin and affiliate address

- integration-test/transaction_watcher_service_test.ts
- migrations/1639527388617-PopulateRfqMakerPairsTable.ts
- package.json
- src/app.ts
- src/config.ts
- src/constants.ts
- src/handlers/meta_transaction_handlers.ts
- src/handlers/swap_handlers.ts
- src/schemas/swap_quote_request_schema.json
- src/services/swap_service.ts
- src/types.ts
- src/utils/address_utils.ts
- src/utils/config_manager.ts
- src/utils/price_comparison_utils.ts
- src/utils/rfq_blockchain_utils.ts
- src/utils/slippage_model_fill_adjustor.ts
- src/utils/slippage_model_manager.ts
- test/constants.ts
- test/price_comparison_utils_test.ts
- test/rfq_blockchain_utils_test.ts
- test/rfqt_test.ts
- test/swap_test.ts
- test/utils/orders.ts
- yarn.lock
https://github.com/0xProject/protocol/pull/480
* Re-exported `contract-addresses` from `asset-swapper` to avoid a footgun of different versions
* Added a `FillAdjustor` using the `SlippageModelManager`
* Added `enableSlippageProtection` for integrators to signal whether they want slippage adjusted routing based on the slippage model
* [enableSlippageProtection=false](https://metabase.spaceship.0x.org/dashboard/186?run_id=disabled-slippage-protect&adjusted_amount_bought_win_tolerance__bps_=5) should observe very little difference as the changes are disabled.
* [enableSlippageProtection=true]()
- …
> feat: SlippageProtection Use Fill Adjustment in Phase2 of routing.

- package.json
- src/constants.ts
- yarn.lock
> feat: Enable slippage protection by default

- src/runners/rfq_maker_balance_cache_runner.ts
We are running into `execution reverted` errors on the balance cache checker. Haven't done an RCA but increasing the gas limit on the eth_call shouldn't hurt.
> chore: increase gas limit on balance checks

- .github/workflows/deploy.yml
> fix: correct github workflow syntax

- package.json
- src/utils/rfq_dyanmic_blacklist.ts
- yarn.lock
> chore: Upgrade typescript and some other deps to match the versions used in `asset-swapper` [TKR-484]

- src/asset-swapper/swap_quoter.ts
- src/asset-swapper/utils/market_operation_utils/constants.ts
- src/asset-swapper/utils/market_operation_utils/index.ts
- src/asset-swapper/utils/market_operation_utils/orders.ts
- src/asset-swapper/utils/market_operation_utils/pools_cache/balancer_v2_swap_info_cache.ts
- src/asset-swapper/utils/market_operation_utils/types.ts
- src/asset-swapper/utils/utils.ts
- test/asset-swapper/global_hooks.ts
- test/asset-swapper/market_operation_utils_test.ts
> chore: Remove various dead code [TKR-534]

- src/asset-swapper/index.ts
- src/asset-swapper/types.ts
- src/asset-swapper/utils/market_operation_utils/index.ts
- src/asset-swapper/utils/market_operation_utils/path_optimizer.ts
- src/asset-swapper/utils/market_operation_utils/types.ts
- src/services/swap_service.ts
- src/utils/sampler_metrics.ts
* Refactor `SamplerMetrics` before start logging sampler `buy` gas usage. 
* While `SamplerMetrics` is optional in a few places they were never undefined. 
> chore: Refactor SamplerMetrics [TKR-534]

- src/asset-swapper/utils/market_operation_utils/index.ts
- src/utils/sampler_metrics.ts
> feat: Log sampler buy gas usage [TKR-498]

- src/config.ts
> fix: Disable `Balancer` temporarily

- package.json
- src/asset-swapper/quote_consumers/exchange_proxy_swap_quote_consumer.ts
- src/asset-swapper/utils/alt_mm_implementation_utils.ts
- src/asset-swapper/utils/market_operation_utils/index.ts
- src/asset-swapper/utils/market_operation_utils/orders.ts
- src/asset-swapper/utils/market_operation_utils/sampler_operations.ts
- src/asset-swapper/utils/market_operation_utils/types.ts
- src/asset-swapper/utils/quote_requestor.ts
- src/asset-swapper/utils/rfq_maker_blacklist.ts
- src/config.ts
- src/rpc_subprovider.ts
- src/runners/rfq_maker_balance_cache_runner.ts
- src/services/websocket_service.ts
- src/utils/slippage_model_manager.ts
- test/constants.ts
- test/utils/quote_comparison_utils_test.ts
* Fixed/suppressed all `eslint` errors
* Add `eslint` (error only) to `yarn list` (enables `eslint` in CI)
> chore: Fix `eslint` errors and add `eslint` to `yarn lint`[TKR-529]

- src/services/swap_service.ts
Adding a temporary sanity check on `useRfqClient` 
> chore: add a temporary log on useRfqClient

- src/services/swap_service.ts
> chore: revert 25809c224bf63ff1f3b56ae076c3db19c16b3b26

- src/asset-swapper/utils/market_operation_utils/orders.ts
- src/config.ts
* Balancer V1 bridge data encoder code was accidentally deleted in https://github.com/0xProject/protocol/pull/546
* Restore the deleted code and remove Balancer V1 from excluded sources.
> fix: Fix Balancer V1 bug [TKR-549]

- package.json
> chore: Set eslint --max-warnings instead of --quiet

- src/asset-swapper/utils/market_operation_utils/bridge_source_utils.ts
- src/asset-swapper/utils/market_operation_utils/constants.ts
- src/asset-swapper/utils/market_operation_utils/types.ts
* Original PR: #943 
* Adjust gas schedule for a few pools 
* Temporarily disable Saddle on Arbitrum
> feat: Update Saddle pools (Ethereum, Optimism) [TKR-543]

- src/handlers/meta_transaction_handlers.ts
- src/schemas/meta_transaction_quote_request_schema.json
- src/services/meta_transaction_service.ts
- src/types.ts
Update meta transaction service to add quote report
- Add integrator ID to request schema + type
- Add kafka to metatransaction service
> feat: Add quote report to metatransaction service

- src/handlers/meta_transaction_handlers.ts
- src/services/meta_transaction_service.ts
- src/types.ts
Goes on top of #968.
Get rid of a bunch of nastiness in the meta transaction code.
- Align function names and types
- Add a comment here and there
- Remove old quote report stuff
- Sort things
- Remove API key code
> chore: Clean up meta transaction names and types

- package.json
- src/asset-swapper/utils/market_operation_utils/bridge_source_utils.ts
- src/asset-swapper/utils/market_operation_utils/constants.ts
[Simbot Results for Curve V2](https://metabase.spaceship.0x.org/dashboard/186?run_id=improvise-obscene-letter&adjusted_amount_bought_win_tolerance__bps_=1.0)
> fix: Curve V2 on Arbitrum [TKR-560]

- src/asset-swapper/utils/market_operation_utils/constants.ts
* Disable Synapse on Arbitrum until it's fixed.
* Lowercase Arbitrum token addresses.
> fix: Disable Synapse on Arbitrum [TKR-558]

- src/asset-swapper/utils/market_operation_utils/constants.ts
- src/asset-swapper/utils/market_operation_utils/orders.ts
- src/asset-swapper/utils/market_operation_utils/sampler_operations.ts
- src/asset-swapper/utils/market_operation_utils/types.ts
- test/asset-swapper/dex_sampler_test.ts
> feat: update gas schedule for arbitrum sources

- src/asset-swapper/utils/market_operation_utils/constants.ts
upped gas significantly for all sources until kyu's gas calculations are in effect
> feat: turn on the gas pump

- src/asset-swapper/utils/market_operation_utils/constants.ts
> feat: add multihop to arbitrum and goerli

- src/asset-swapper/utils/market_operation_utils/constants.ts
[Simbot run for nUSD LP](https://metabase.spaceship.0x.org/dashboard/186?run_id=strike-even-sweater&adjusted_amount_bought_win_tolerance__bps_=1.0)
[Simbot run for nETH LP](https://metabase.spaceship.0x.org/dashboard/186?run_id=supply-enchanting-side&adjusted_amount_bought_win_tolerance__bps_=1.0)
For more information see `0x API Matcha smoke …
> feat: enabling Synapse on Arbitrum [TKR-558]

- src/asset-swapper/utils/quote_report_generator.ts
- src/services/meta_transaction_service.ts
- src/utils/quote_report_utils.ts
- Remove unused metatx quote report type
- Add gaslessSwapAmm option to quote report
- Use in metatransaction service
> feat: Add gaslessSwapAmm option to quote report + use in metatransaction service

- src/handlers/swap_handlers.ts
- src/services/meta_transaction_service.ts
- src/utils/quote_report_utils.ts
Nobody used this.
Remove related types and utility functions
> chore: Remove logQuoteReport

- src/asset-swapper/utils/market_operation_utils/constants.ts
Adding the following pools:
[MIM Pool](https://arbitrum.curve.fi/factory/0):
[Pool Address](https://arbiscan.io/address/0x30dF229cefa463e991e29D42DB0bae2e122B2AC7)
[vstFRAX Pool](https://arbitrum.curve.fi/factory/19):
[Pool Address](https://arbiscan.io/address/0x59bF0545FCa0E5Ad48E13DA269faCD2E8C886Ba4)
[fraxBP Pool](https://arbitrum.curve.fi/factory/41):
[Pool Address](https://arbiscan.io/address/0xC9B8a3FDECB9D5b218d02555a8Baf332E5B740d5)
[MIM Pool SimBot Run](https://metabase.spaceship.0x.org/dashboard/186?run_id=hand-slippery-crowd&adjusted_amount_bought_win_tolerance__bps_=1.0)
[fraxBP Pool SimBot Run](https://metabase.spaceship.0x.org/dashboard/186?run_id=wish-dizzy-store&adjusted_amount_bought_win_tolerance__bps_=1.0)
[vstFRAX Pool SimBot …
> feat: enabling additional Arbitrum Curve pools [TKR-566]

- src/asset-swapper/utils/market_operation_utils/constants.ts
- src/asset-swapper/utils/market_operation_utils/pools_cache/sgPoolDataService.ts
> fix: Balancer v2 on Arbitrum [TKR-559]

- .eslintrc.json
- package.json
- src/app.ts
- src/asset-swapper/swap_quoter.ts
* Add `argsIgnorePattern` for `no-unused-vars`
* Fix a few eslint warnings
> chore: Add `argsIgnorePattern` for `no-unused-vars`

- package.json
- yarn.lock
> feat: upgrading 0x/api-utils to gather data on API errors [TKR-436]

- src/handlers/swap_handlers.ts
- src/routers/swap_router.ts
> chore: remove /tokens endpoint and related code [TKR-602]

- package.json
- src/asset-swapper/quote_consumers/exchange_proxy_swap_quote_consumer.ts
- src/asset-swapper/quote_consumers/multiplex_encoders.ts
- src/asset-swapper/quote_consumers/quote_consumer_utils.ts
- src/asset-swapper/utils/market_operation_utils/types.ts
- src/asset-swapper/utils/quote_report_generator.ts
- yarn.lock
This reverts commit 967e4181988ea890626e3545c80f1e694e8d2610. (#979)
It broke FQT (`InvalidTransformDataError`). It's likely that the change was not backward compatible. 
> fix: Revert "feat: rfqtv2 calldata generation (#979)"

- src/asset-swapper/utils/market_operation_utils/constants.ts
An integrator let us know that UbeSwap offers a much better price on the cREAL/cEUR pair than what is currently returned by the 0x API. I've added cUSD as an intermediate token on Celo in order to improve our routing for this pair.
Current API response: 
After adding cUSD as an intermediate token:
Compare [current API response](https://celo.api.0x.org/swap/v1/quote?buyToken=0xe8537a3d056DA446677B9E9d6c5dB704EaAb4787&sellToken=cEUR&sellAmount=1000000000000000000) and the same API request on your local machine: http://localhost:3000/swap/v1/quote?buyToken=0xe8537a3d056DA446677B9E9d6c5dB704EaAb4787&sellToken=cEUR&sellAmount=1000000000000000000.
- …
> fix: Add cUSD as an intermediate token for Celo

- src/asset-swapper/utils/market_operation_utils/constants.ts
- src/asset-swapper/utils/market_operation_utils/sampler_operations.ts
> fix: Do not use Uniswap v2 for stETH

- contracts/src/UniswapV3Sampler.sol
This PR changes how `UniswapV3Sampler` samples different pools/paths in a pretty significant way. Previously, it did a brute force sampling for all possible paths for all sampling amounts (13). There are maximum 4 pools (4 fee tiers) so there are maximum of 4 paths for one hop and maximum of 16 (4x4) paths for two hop. 
Given a token pair, however, it is extremely unlikely that all 4 pools are liquid. The change in this PR finds the top 2 liquid pools and limits the search space to those liquid pools rather than repeatedly sampling against illiquid pools.
To give an example, for a two-hop, say `A -> B -> C`, instead of searching maximum of 16 (4x4) paths for 13 sampling amounts, the new sampler first find two most liquid pools for `A -> B` and two most liquid pools for `B -> C` and only …
> feat: Optimize `UniswapV3Sampler` gas usage [TKR-551]

- src/asset-swapper/utils/market_operation_utils/sampler_operations.ts
> fix: Do not use Uniswap v3 for stETH

- README.md
Adding Twitter button + fix minor typo
> Adding Twitter button + fix minor typo

- package.json
- src/app.ts
- src/asset-swapper/utils/market_operation_utils/constants.ts
- src/config.ts
- yarn.lock
> chore: Remove Ropsten and Rinkeby references [TKR-603]

- src/asset-swapper/quote_consumers/exchange_proxy_swap_quote_consumer.ts
fixed issue that broke buying native tokens with Meta txn
> fix: fixing issue that broke buying native token

- src/services/swap_service.ts
added error when buyAmount would be less than zero
tested in simbot
> feat: adding error when buyAmount would be negative, likely because of fees

- src/config.ts
- src/utils/service_utils.ts
Use config variable to switch on/off gasless swap fee for meta-transaction to give us finer level of control until we have decided how to present this fee to the caller and communicate with the integrators
> chore: Use config variable to switch on/off gasless swap fee for meta-transaction

- src/asset-swapper/utils/market_operation_utils/constants.ts
> feat: add buy support for aaveV2 on mainnet

- src/asset-swapper/utils/market_operation_utils/constants.ts
> feat: Lower native token amount to 0.1 ether on Optimism and Arbitrum

- package.json
- src/asset-swapper/quote_consumers/exchange_proxy_swap_quote_consumer.ts
- src/asset-swapper/quote_consumers/multiplex_encoders.ts
- src/asset-swapper/quote_consumers/quote_consumer_utils.ts
- src/asset-swapper/utils/market_operation_utils/types.ts
- src/asset-swapper/utils/quote_report_generator.ts
- test/asset-swapper/market_operation_utils_test.ts
- yarn.lock
> fix: RFQTV2 reintroduce previous FQT PR [TKR-619]

- .prettierignore
- package.json
- src/asset-swapper/utils/market_operation_utils/index.ts
- src/asset-swapper/utils/market_operation_utils/path_optimizer.ts
> chore: Minor cleanup in `market_operation_utils` [TKR-623]

- src/asset-swapper/utils/market_operation_utils/index.ts
> chore: Add additional logging for NoOptimalPath error [TKR-436]

- package.json
- yarn.lock
> chore: Bump @0x/contract-addresses for BalancerV2Batch support on Fantom [TKR-630]

- src/asset-swapper/utils/market_operation_utils/index.ts
added prometheus counter for zero native conversion
spin up API
make query with token that will cause zero conversion to native.
> chore: adding prom counter for zero conversion

- src/asset-swapper/utils/market_operation_utils/constants.ts
- test/asset-swapper/gas_schedule_test.ts
Tweak the default gas schedule for OtcOrder.
Adds unit tests to solidify the behavior.
> chore: tweak gas schedule for OtcOrder

- test/asset-swapper/pools_cache_test.ts
> fix: Skip flaky BalancerV2PoolsCache test

- src/asset-swapper/utils/market_operation_utils/constants.ts
> chore: ycrv, bLUSD, rsr curve pools

- package.json
- yarn.lock
* Fee-related transformers upgrade for smart contract wallet support
> feat: Upgrade `@0x/contract-addresses` [TKR-587]

- package.json
- src/asset-swapper/utils/protocol_fee_utils.ts
- src/db_connection.ts
* Some top level tests `test/*_test.ts` were skipped due to a typo in `test:rest` script.
* Fix broken/flaky tests due to how `ProtocolFeeUtils` singleton is initialized.
> fix: Re-included skipped tests [TKR-651]

- src/handlers/swap_handlers.ts
- src/routers/swap_router.ts
- src/services/swap_service.ts
- src/types.ts
> chore: Remove `prices` endpoint [TKR-653]

- src/asset-swapper/utils/market_operation_utils/constants.ts
> fix: temporarily disable ironbank

- src/asset-swapper/utils/market_operation_utils/orders.ts
* Chain specific comments (e.g. Avalanche) is misleading as many protocols are multichain.
* Also inline couple encoders that are only used once.
> chore: Remove chain comment in `BRIDGE_ENCODERS`

- package.json
- src/asset-swapper/utils/market_operation_utils/constants.ts
- src/asset-swapper/utils/market_operation_utils/orders.ts
- src/asset-swapper/utils/market_operation_utils/sampler_operations.ts
- src/asset-swapper/utils/market_operation_utils/types.ts
- yarn.lock
* Add Dystopia as a liquidity source
* Simbot run https://metabase.spaceship.0x.org/dashboard/186?run_id=undress-wooden-cannon&adjusted_amount_bought_win_tolerance__bps_=1.0
> feat: Add Dystopia as a liquidity source

- test/asset-swapper/utils/market_operations_utils/path_optimizer_test.ts
Add tests to cover:
* Single native source routing
* DEX multiplex routing
> chore: Add more `PathOptimizer` tests (part 1) [TKR-637]

- test/asset-swapper/utils/market_operations_utils/path_optimizer_test.ts
* Add more test cases for multiplex routing (DEX + native, native + native)
> chore: Add multiplex test cases for `PathOptimizer` (part 2) [TKR-637]

- src/asset-swapper/swap_quoter.ts
Delete unused `getBatchMarketBuySwapQuoteAsync` in `SwapQuoter`
n/a  -- deleted deadcode. 
> chore: Delete unused `getBatchMarketBuySwapQuoteAsync` in `SwapQuoter` [LIT-623]

- src/asset-swapper/quote_consumers/exchange_proxy_swap_quote_consumer.ts
- src/asset-swapper/quote_consumers/quote_consumer_utils.ts
- src/asset-swapper/swap_quoter.ts
- src/asset-swapper/types.ts
- src/asset-swapper/utils/market_operation_utils/orders.ts
- src/asset-swapper/utils/market_operation_utils/path.ts
- src/asset-swapper/utils/market_operation_utils/types.ts
- src/asset-swapper/utils/quote_simulation.ts
- test/asset-swapper/exchange_proxy_swap_quote_consumer_test.ts
- test/asset-swapper/quote_simulation_test.ts
* Group optimized native orders under `OptimizedNativeMarketOrder`
* Simple refactoring -- passes existing unit tets.
> chore: Create a `OptimizedMarketOrder` subtype `OptimizedNativeMarketOrder` [LIT-690]

- .github/workflows/ci-build.yml
> chore: add circular deps check to ci

- src/asset-swapper/swap_quoter.ts
- src/asset-swapper/types.ts
- src/config.ts
- src/services/swap_service.ts
- test/swap_test.ts
Remove default excluded sources and consolidate bridge source configuration
* For determining whether limit order is enabled, use buy/sell quote sources instead of relying on default excluded list
* Manual testing 
* [Simbot sanity run](https://metabase.spaceship.0x.org/dashboard/186?run_id=2022-12-excluded-sources)
> chore: Remove default excluded sources [LIT-690]

- src/asset-swapper/utils/market_operation_utils/constants.ts
> chore: Add cTokens to Adjacency List

- package.json
- src/asset-swapper/utils/market_operation_utils/constants.ts
- src/config.ts
- yarn.lock
* Upgrade `@0x/contract-addresses` and remove `Kovan` and `ArbitrumRinkeby` 
* n/a
> chore: Remove `Kovan` and `ArbitrumRinkeby` from `ChainId` [LIT-723]

- .ts-prunerc
- package.json
> chore: adding generated directories to ts-prune ignore

- .eslintrc.json
- package.json
- src/asset-swapper/utils/market_operation_utils/bancor_service.ts
- src/asset-swapper/utils/market_operation_utils/constants.ts
- src/asset-swapper/utils/market_operation_utils/pools_cache/balancer_v2_swap_info_cache.ts
- test/utils/rfq_blocked_address_utils_test.ts
- test/utils/slippage_model_manager_test.ts
- yarn.lock
Added zappers eslint rule to require addresses be lowercase. I fixed the issues that it found. I used a VIM macro to lower case the text but please take a look to make sure the addresses look correct (i'll do the same). 
> chore: add zapper address linter

- src/services/swap_service.ts
> chore: fixing error message

- src/asset-swapper/utils/market_operation_utils/index.ts
- src/asset-swapper/utils/market_operation_utils/path.ts
- src/asset-swapper/utils/market_operation_utils/path_optimizer.ts
- test/asset-swapper/utils/market_operations_utils/path_optimizer_test.ts
* Remove unused `bestRate` method
* Remove unused option `gasPrice`
* Remove unused default parameters
* no-op refactoring
> chore: Clean up `Path` code [LIT-690]

- src/asset-swapper/utils/market_operation_utils/path.ts
- test/asset-swapper/utils/market_operations_utils/path_test.ts
* Remove `_size` in `Path` as it's redundant 
* Add tests for `adjustedRate()`
* Make `adjustedSize()` and `adjustedCompleteRate()` private 
* Added new unit tests.
> chore: Remove `_size` in `Path` and add some tests for `adjustedRate()` [LIT-690]

- src/asset-swapper/utils/market_operation_utils/index.ts
- src/asset-swapper/utils/market_operation_utils/orders.ts
- src/asset-swapper/utils/market_operation_utils/path.ts
- src/asset-swapper/utils/market_operation_utils/path_optimizer.ts
- src/asset-swapper/utils/market_operation_utils/types.ts
- test/asset-swapper/utils/market_operations_utils/path_optimizer_test.ts
- test/asset-swapper/utils/market_operations_utils/path_test.ts
* Remove `Path.createOrders` parameter
* Introduce `PathContext` to `Path`
* Unit tests
> chore: Remove `Path.createOrders` parameter [LIT-690]

- src/asset-swapper/swap_quoter.ts
- src/asset-swapper/utils/market_operation_utils/index.ts
- src/asset-swapper/utils/market_operation_utils/types.ts
- test/asset-swapper/market_operation_utils_test.ts
* Replace `optimizedOrders`, `sourceFlags`, `liquidityDelivered` and `adjustedRate` with `Path
* Refactoring PR - passes all unit tests.
> chore: Replace a few fields in `OptimizerResult` with `Path` [LIT-690]

- src/asset-swapper/swap_quoter.ts
- src/asset-swapper/types.ts
- src/asset-swapper/utils/market_operation_utils/constants.ts
- src/asset-swapper/utils/market_operation_utils/index.ts
- src/asset-swapper/utils/market_operation_utils/path.ts
- test/asset-swapper/utils/market_operations_utils/path_test.ts
* Implement `Path.hasTwoHop`
* Added unit tests.
> chore: Implement `Path.hasTwoHop` [LIT-690]

- src/asset-swapper/swap_quoter.ts
- src/asset-swapper/utils/quote_info.ts
- test/asset-swapper/utils/market_operations_utils/quote_info_test.ts
* Move quote info calculation logic to `quote_info.ts` and add some tests
* Added unit tests.
> chore: Move quote info calculation logic to `quote_info.ts` and add some tests [LIT-690]

- src/asset-swapper/utils/market_operation_utils/path.ts
- test/asset-swapper/utils/market_operations_utils/path_test.ts
* Implement `Path.getSlippedOrdersByType`
* which will be used instead of `Path.getSlippedOrders` in certain places (if not all)
* Added unit tests.
> chore: Implement `Path.getSlippedOrdersByType` [LIT-690]

- test/asset-swapper/utils/market_operations_utils/gas_price_utils_test.ts
Rename `protocol_fee_utils_test.ts` to `gas_price_utils_test.ts` to reflect its changed name (`GasPriceUtils`)
* Renamed an existing test file 
> chore: Rename `protocol_fee_utils_test.ts` to `gas_price_utils_test.ts`

- src/asset-swapper/quote_consumers/exchange_proxy_swap_quote_consumer.ts
* Fix incorrect assertion in `encodeMultiplexMultiHopFillCalldata`
*  [simbot run](https://metabase.spaceship.0x.org/dashboard/186?run_id=2023-01-fix-multiplex-feat)
> fix: Fix assertion in `encodeMultiplexMultiHopFillCalldata`

- src/asset-swapper/utils/market_operation_utils/sampler_operations.ts
- src/samplers/uniswapv3_sampler.ts
- test/asset-swapper/dex_sampler_test.ts
- test/asset-swapper/utils/mock_sampler_contract.ts
Refactor UniswapV3 sampler operation creation in preparation for adding more tick-based AMMs.
Added unit tests.
Simbot run: https://metabase.spaceship.0x.org/dashboard/186?run_id=kevin-test-uniswapv3-refactor&adjusted_amount_bought_win_tolerance__bps_=1.0
> refactor: Uniswapv3 sampler operation creation

- contracts/foundry.toml
- contracts/src/UniswapV3Common.sol
- contracts/src/UniswapV3MultiQuoter.sol
- contracts/src/interfaces/IUniswapV3.sol
- contracts/src/test/UniswapV3Sampler.t.sol
- package.json
- yarn.lock
Initial implementation and sell function UniswapV3MultiQuoter. Note that current UniswapV3Sampler doesn't use this yet.
> feat: implementing sell function for UniV3 MultiQuoter [LIT-763]

- package.json
- src/asset-swapper/utils/market_operation_utils/constants.ts
- yarn.lock
* Introduce `immtuable.js`
* Replace native `Set`s with `immtuable`'s in `constants.ts` as a start.
> chore: Introduce `immutable.js` [LIT-637]

- src/asset-swapper/utils/market_operation_utils/constants.ts
> chore: add native to polygon source filter

- src/errors.ts
- src/services/swap_service.ts
- src/utils/rfq_client.ts
Ensures that if a request is exclusively asking for RFQt liquidity, but RFQt is not enabled for the chain, the server responds with an explicit error message. Also kills RFQt-v2 rollout mechanism for easier config maintenance.
> feat: add rfqt availability check

- src/errors.ts
- src/services/swap_service.ts
- src/utils/rfq_client.ts
> fix: revert rfqt availability check

- test/asset-swapper/quote_consumer/feature_rules/transform_erc20_rule_test.ts
- test/asset-swapper/test_utils/test_data.ts
* Replace random test objects with deterministic test objects in `transform_erc20_rule_test.ts`
* Test-only changes.
> refactor: Replace random test objects with deterministic test objects in `transform_erc20_rule_test.ts` [LIT-637]

- src/asset-swapper/quote_consumers/exchange_proxy_swap_quote_consumer.ts
> fix: revert "chore: add Polygon to RFQtv2 VIP"

- contracts/src/WooPPSampler.sol
- src/asset-swapper/utils/market_operation_utils/constants.ts
- src/asset-swapper/utils/market_operation_utils/orders.ts
- src/asset-swapper/utils/market_operation_utils/sampler_operations.ts
- src/asset-swapper/utils/market_operation_utils/types.ts
> chore: Revert "feat: WooFi V2 [LIT-755]"

- .github/workflows/docker-on-demand.yml
- .prettierrc
Add an experimental workflow to build and push docker image on demand from a branch. 
* n/a
> chore: Add GitHub action to build docker image on demand

- .github/workflows/docker-on-demand.yml
> fix: Remove unnecessary workflow input

- contracts/src/WooPPSampler.sol
- src/asset-swapper/utils/market_operation_utils/constants.ts
- src/asset-swapper/utils/market_operation_utils/orders.ts
- src/asset-swapper/utils/market_operation_utils/sampler_operations.ts
- src/asset-swapper/utils/market_operation_utils/types.ts
> chore: Revert "chore: Revert "feat: WooFi V2 [LIT-755]""

- contracts/src/WooPPSampler.sol
- src/asset-swapper/utils/market_operation_utils/constants.ts
- src/asset-swapper/utils/market_operation_utils/orders.ts
- src/asset-swapper/utils/market_operation_utils/sampler_operations.ts
- src/asset-swapper/utils/market_operation_utils/types.ts
> chore: Revert "chore: Revert "chore: Revert "feat: WooFi V2 [LIT-755]"""

- src/asset-swapper/utils/market_operation_utils/index.ts
Use fee sources only when a swap size is extremely small (Optimism)
* Extremely small size (sub $1) is often over-optimized and routed to a niche liquidity (e.g. $50 TVL pool) and causes high revert rate.
* Introduce a concept of micro swap (defined as 1% of native fee token amount (from `NATIVE_FEE_TOKEN_AMOUNT_BY_CHAIN_ID`) and only route to fee sources and disable multi-hop.
* On Optimism, that would translate to a swap size less than 1/1000 ETH.
* As an experimental feature, it's only enabled on Optimism to begin with.
* [Simbot run](https://metabase.spaceship.0x.org/dashboard/186?run_id=micro-swap-10c-100c--fix-v2&adjusted_amount_bought_win_tolerance__bps_=1.0) on $0.01-$1 (to verify the fix).
* [Simbot run](https://metabase.spaceship.0x.org/dashboard/186?run_id=micro-swap-fix-v2-all& …
> fix: Use fee sources only when a swap size is extremely small (Optimism) [LIT-811]

- src/asset-swapper/swap_quoter.ts
- src/asset-swapper/types.ts
- src/asset-swapper/utils/market_operation_utils/index.ts
- src/services/swap_service.ts
- src/types.ts
> feat: pass in gasless rfqt params to rfq client

- src/services/swap_service.ts
> chore: add debug log for positive slippage

- src/asset-swapper/utils/market_operation_utils/types.ts
> chore: remove deprecated curve function selectors [LIT-832]

- src/handlers/meta_transaction_handlers.ts
There are meta-transaction quote errors in zero/g since yesterday evening. Adding more context to debug https://grafana.spaceship.0x.org/d/NcG1f844k/zero-g-api?orgId=1&from=now-12h&to=now&viewPanel=17
> chore: Update error log in meta-transaction handlers for uncaught exceptions

- src/handlers/meta_transaction_handlers.ts
- src/types.ts
- src/utils/fee_calculator.ts
- test/utils/fee_calculator_test.ts
Add `billingType` to fees:
- Add field to TS types
- Update calculator functions
- Fix a bug in calculator function
> chore: Add `billingType` to fees [RFQ-827]

- src/errors.ts
- src/handlers/meta_transaction_handlers.ts
- src/services/meta_transaction_service.ts
- src/types.ts
- test/meta_transaction_test.ts
Initially, meta-transaction v2 endpoints are designed to only handle meta-transaction v2 types. However, there is a new use case that needs v2 endpoints to support existing meta-transaction. This PR makes the corresponding changes.
> chore: Refactor meta-transaction v2 to handle different meta-transaction types [RFQ-828]

- scripts/curve_automation.ts
> suggested changes to curve_automation.ts

- src/services/swap_service.ts
- src/types.ts
- test/swap_test.ts
Adding block number to debugData
N/A
> feat: adding blockNumber to debugData [LIT-854]

- src/middleware/address_normalizer.ts
- src/utils/address_utils.ts
- test/asset-swapper/market_operation_utils_test.ts
I'm not sure what exactly the difference is in the TS setup in `0x-labs` is but the build is failing on these few things.
> fix: Fix up some types

- package.json
- tsconfig.json
> chore: Tweak json configs

- src/asset-swapper/utils/market_operation_utils/orders.ts
> fix: UniswapV3 filtering out bad path encodings [LIT-865]

- src/orderbook/asset_swapper_orderbook.ts
*  Add a counter for orderbook requests
> chore: Add a counter for orderbook requests [LIT-852]

- src/runners/http_sra_service_runner.ts
https://www.npmjs.com/package/express-prom-bundle
> feat: Enable method on prometheus stats to distinguish "PUT" and "GET" for /orders
