package.json, src/config.ts, src/handlers/mesh_gateway_handlers.ts, src/index.ts, src/middleware/error_handling.ts, src/runners/http_service_runner.ts, src/services/orderbook_service.ts, src/utils/mesh_utils.ts, yarn.lock
The main attempt here is to make sure the HTTP service can still run when mesh is down or we cannot connect to mesh. Unfortunately the mesh RPC client has an unhandled promise rejection when the you give it an invalid URL. By default, unhandled promise rejections are warnings, and do not crash your app, so I have implemented the same here for the custom rejection handlers. By default, an uncaught **exception** does crash your app. The point with catching them here is to have all logs be formatted in the same way.
There are also some other clean-up items in here.
=> More cleanup and hardening

.drone.yml
About
===
This PR adds a simple `.drone.yml` config that builds the images and ships them to ECR,
Note:
- The repository itself needs to be activated on Drone.
- `ECR_REPO` and `ECR_REGISTRY` need to be set in the Drone secrets first.
=> add .drone.yml for Docker build and ship to ECR

src/constants.ts, src/handlers/sra_handlers.ts, src/index.ts, src/routers/sra_router.ts, src/runners/http_service_runner.ts, src/services/sra_http_service.ts, src/services/websocket_service.ts
This PR renames `/mesh_gateway` endpoints to `/sra`. Also renames files and classes.
Motivation for this is the `MeshGateway` endpoints support the SRA spec. Connection to Mesh is more of an implementation detail.
=> Rename /mesh_gateway to /sra

src/services/websocket_service.ts
The connect client throws an error when you do not pass any object in the `subscribe` call. That is questionable on its own, but the API should definitely be handling that as an `ALL_SUBSCRIPTION_OPTS` instead of a subscription that listens to nothing.
=> Treat empty subscription object as ALL_SUBSCRIPTION_OPTS

src/index.ts, src/logger.ts
This PR adds logging for incoming requests. 
I tried out using `express-pino-logger` but found it too restrictive. The supported serializers coerced `Express.Request` and `Express.Response` into `IncomingMessage` and `ServerResponse` from the native 'http' module, which doesn't easily expose the request body or params. 
So instead I wrote our own little middleware. It's pretty simple but hopefully useful.
One of the features is that all requests have the logger object attached. So you can do:
```
public async ordersAsync(req: express.Request, res: express.Response): Promise<void> {
req.logger.info(`Retrieving orders!`);
// handle the request
}
```
Some examples of the logs produced:
(With pino-pretty in dev mode; actual logs won't have so much whitespace)
@alexkroeger , I'm not separating …
=> Add request logging

src/handlers/staking_handlers.ts, src/routers/staking_router.ts, src/services/staking_data_service.ts, src/types.ts, src/utils/staking_utils.ts
Once we agree with the format we will have to change the frontend as well.
**staking/pools**
```
{
stakingPools: [
{
poolId: "1",
operatorAddress: "0x5409ed021d9299bf6814279a6a1411a7e866a631",
createdAt: {
blockNumber: 14491738,
txHash: "0xea30da4f4a5ccb209fe7861c71b0c365684af076924a23e48a9028c8b7e13e5b"
},
metaData: {
name: "Over 9000",
bio: "All your stake are belong to us",
location: "San Francisco, CA",
isVerified: false,
logoUrl: "https://github.com/0xProject/0x-staking-pool-registry/raw/master/logos/0x.png",
websiteUrl: "http://0x.org"
},
sevenDayProtocolFeesGeneratedInEth: 0,
currentEpochStats: {
poolId: "1",
zrxStaked: 31260.31,
operatorShare: 0.000004,
approximateStakeRatio: 0,
makerAddresses: [ ],
totalProtocolFeesGeneratedInEth: 0
},
nextEpochStats: {
poolId: "1",
zrxStaked: …
```
=> Staking/stats, staking/epochs, change staking/pools

src/services/staking_data_service.ts
{
currentEpoch: {
epochId: 9,
epochStart: {
blockNumber: 15393965,
txHash: "0x7894c41084156e223aa6f331ec6ad759870dd804e24e4552411cdae0c27a00df",
timestamp: "2019-12-12T00:47:32.000Z"
},
zrxDeposited: 39163.23,
zrxStaked: 38096.48,
protocolFeesGeneratedInEth: 0
},
nextEpoch: {
epochId: 10,
epochStart: {
blockNumber: 15422765,
timestamp: "2019-12-17T00:47:32.000Z"
},
zrxDeposited: 39164.23,
zrxStaked: 38096.48,
protocolFeesGeneratedInEth: 0
}
}
=> Fix query typo

src/config.ts, src/constants.ts, src/logger.ts
About
===
This PR adds an envvar `DEFAULT_LOGGER_INCLUDE_TIMESTAMP` which if set to `false` will make sure `pino` will not include the timestamp in its output.
=> Add option to configure `time` field in default logger

src/services/staking_data_service.ts
Currently returns 500 with reason:
```
{
"reason": "Could not find pool with pool_id 600"
}
```
Should be a 404; 500 should be reserved for critical errors that need our attention
=> Return 404 when user requests a non-existent staking pool id

package.json, src/constants.ts, src/middleware/request_logger.ts, src/services/swap_service.ts, src/utils/order_utils.ts
All bridge orders now set the `feeRecipientAddress` to the specified `FEE_RECIPIENT_ADDRESS`, this allows for a basic attribution when a taker fills the quote.
The Forwarder will also have the `feeRecipient` set to the `FEE_RECIPIENT_ADDRESS`.
For example, `FEE_RECIPIENT_ADDRESS = 0x0000000000000000000000000000000000000001`
decoded call data
```json
{
"functionName": "marketSellOrdersWithEth",
"functionSignature": "marketSellOrdersWithEth((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes,bytes,bytes)[],bytes[],uint256,address)",
"functionArguments": {
"orders": [
{
"makerAddress": "0x0ac2d6f5f5afc669d3ca38f830dad2b4f238ad3f",
"feeRecipientAddress": "0x0000000000000000000000000000000000000001",
"makerAssetData": …
```
=> Attribute swap quotes to fee recipient address

src/config.ts, src/handlers/swap_handlers.ts, src/routers/swap_router.ts
Basic functionality for lighter clients to discover a list of all tokens available and their symbol.
This does not check for any available liquidity in either the database or in bridges. 
Rather than have a list of 2 tokens in the whitelist (when `WHITELIST_ALL_TOKENS` is unspecified) use the token metadata to populate this list.
=> Implement basic /swap/tokens endpoint

src/utils/order_utils.ts
This PR adds support for other asset data types, and fixes #57
Initially I tried filtering out non-ERC20/ERC721 orders before retrieving asset pairs, then realised that the related functions in `order_utils.ts` were also used more generally by the orderbook when getting orders or checking for existence of asset pairs. Seems like it would be a non-trivial refactor, and it's unclear to me what the implications of that refactor would be, e.g. seems undesirable if `orderbook.getOrders` only returns ERC20/ERC721 orders.
I'm unsure of the appropriate default values for ERC1155, MultiAsset, StaticCall, and ERC20Bridge, so this PR is a bit of a WIP. 
Deployed to Kovan and it successfully returns ERC1155 asset pairs instead of throwing a server error. Compare with failing screenshot in #57:
=> stop throwing errors for non-ERC20/ERC721 asset data

src/constants.ts
Return Native only ordders for testnets by disabling all Bridges. There is some liquidity for Kovan on ZRX.
`curl 'http://localhost:3000/swap/quote?buyToken=ZRX&sellToken=WETH&buyAmount=1000'`
```json
{
"price": "100",
"to": "0x61935cbdd02287b511119ddb11aeb42f1593b7ef",
"data": "0x8bc8efb3000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000003e8000000000000000000000000000000000000000000000000000000000000034000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000a31f3d5d0d8a412084a3f83d253340524f7f88970000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a31f3d5d0d8a412084a3f83d253340524f7f88 …
```
=> Disable Bridge sources for Testnets

src/services/swap_service.ts
Query for decimals on the token contract if not mapped. Log if this is unmapped for future updates.
Sampling also has a requirement on decimals, so we can assume that if decimals is not present on the token then it is unlikely to be supported by the API/Bridge orders.
Note our ERC20 Token does not have `decimals` in the `ABI`, tbh I think we should just fix that and assume it always exists, if not it's the callers problem.
=> Query ERC20Token decimals if not mapped

src/queries/staking_queries.ts
The pool/id endpoint was not returning the correct 7-day fee value, because the associated query returned all pools.
=> the 7-day fee pool query should only return 1 pool

src/token_metadatas_for_networks.ts
SNX has a few proxies and a real token. On-chain liquidity sources use the ProxyERC20.
ProxyERC20: https://etherscan.io/address/0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f#readContract
Real target: https://etherscan.io/address/0x7cb89c509001d25da9938999abfea6740212e5f0#readContract
Proxy??: https://etherscan.io/address/0xc011a72400e58ecd99ee497cf89e3775d4bd732f#readContract
https://api.0x.org/swap/v0/quote?buyToken=0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F&sellToken=ETH&sellAmount=1000000000000000&takerAddress=0xab5801a7d398351b8be11c439e05c5b3259aec9b
=> Update SNX to ProxyERC20 contract

src/queries/staking_queries.ts
The all time pool fees was not including the current epoch, so it was understating all time fees. I fixed the query to include the current epoch.
Testing:
=> Altered all time fees query to take current epoch into account

src/services/swap_service.ts
Parity/Alchemy can return an `error` in the `eth_call` response. `RPCSubprovider` (and `Web3Wrapper`) can throw these in different ways.
[This is performed in the monorepo](https://github.com/0xProject/0x-monorepo/blob/development/packages/base-contract/src/index.ts#L299-L310) but only for calls made directly with the wrappers.
Both INFURA and Alchemy now throw the revert error appropriately.
```json
{
"code": 105,
"reason": "IncompleteFillError",
"values": {
"error": 0,
"expectedAssetFillAmount": "10000000000000000000000",
"actualAssetFillAmount": "0"
}
}
```
=> Throw RevertError when eth call throws an error

src/handlers/swap_handlers.ts, src/schemas/swap_quote_request_schema.json, src/services/swap_service.ts, src/types.ts
- Added a `excludedSources` optional parameter to `/swap/quote` to toggle which sources are used by 0x API.
- Added `sellTokenAddress` and `buyTokenAddress` to `/swap/quote` response.
=> Add `excludedSources` to control sources used by 0x API + add addresses to response.

package.json, src/constants.ts, src/services/swap_service.ts, src/types.ts, yarn.lock
Blocked by publish of asset-swapper with [PR](https://github.com/0xProject/0x-monorepo/pull/2465)
Adds a `source` entry to `/swap/v0/quote` endpoint with breakdown of quote liquidity sources.
Fixed to precision of four decimals for readability.
=> Return sources breakdown for quote

src/handlers/swap_handlers.ts, src/schemas/swap_quote_request_schema.json, src/services/swap_service.ts, src/types.ts
[Example transaction](https://kovan.etherscan.io/tx/0x436b6466c3a00660fa6f8b8f4624a0281907cf4d187c81624486c1b857783a62)
Calldata appended with 
```
fbc019a70000000000000000000000005409ed021d9299bf6814279a6a1411a7e866a631
aka
ZeroExAPIAffiliate(0x5409ed021d9299bf6814279a6a1411a7e866a631)
```
E.g
```
0xa6c3bf33000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000186a000000000000000000000000000000000000000000000000000000000000003c000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000d5a01c9b4e154d483aa57012a1115613df0032b10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```
=> Append Affiliate info to the call data if specified

src/handlers/swap_handlers.ts, src/ormconfig.ts, src/routers/swap_router.ts, src/services/orderbook_service.ts, src/services/swap_service.ts, src/token_metadatas_for_networks.ts, src/types.ts, src/utils/order_store_db_adapter.ts
Currently fetching prices of 1 unit of each token on with a base asset pair (defaults to WETH). I.e buying 1 USDC with WETH. We could make the `unitAmount` configurable by param.
In essence this is similar to performing a quote on every asset with the base asset. So in essence we use Native and Bridge orders. We do this in batches, as at writing this results in concurrent ~4 RPC requests. Currently this takes approximately ~~3.5-5~~ 0.8 seconds to serve the result.
Note:
* We're performing a buy operation (this excludes Kyber)
* We do not perform multiple samples, just the entire amount 
* Base asset defaults to WETH though an alternative base can be supplied. E.g DAI or ZRX
* Some batches are heavier than others due to the order of our Metadata, i.e one batch gets DAI,USDC,ZRX,WBTC and …
=> /prices endpoint

README.md, package.json
Would like to have this before we slap a deprecated sign onto launch-kit backend.
=> Improve documentation about services in the API

src/handlers/sra_handlers.ts, src/routers/sra_router.ts
Currently we only support posting individual orders to 0x API and by extension Mesh. This is inefficient from an ETH RPC order validation perspective and can increase the latency experienced in seeing orders show up for takers. 
This PR adds a non-standard SRA endpoint to post multiple orders to 0x API and by extension Mesh. Since this is a new endpoint, it does not break backward compatibility and can simply be added to 0x API.
=> Add POST /orders endpoint

src/handlers/staking_handlers.ts
Some Web3 providers return checksummed capitalization ETH addresses. Today this leads to nothing being found in the database, however we can support both checksummed and non-checksummed addresses by simply lower casing it before querying the database.
=> Fix staking delegator support checksummed ETH addresses

src/queries/staking_queries.ts, src/types.ts, src/utils/staking_utils.ts
Adds to Market maker stats:
- number of fills (to epoch stats, 7-day stats, and all time stats)
- share of stake (to epoch stats)
- share of fees (to epoch stats)
- share of fills (to epoch stats)
Testing:
=> Added number of fills to pool stats

src/services/swap_service.ts
In the case of someone specifying `takerAddress` we perform an `eth_call` validation and an `estimate_gas` in parallel. The `eth_call` will return a more informative error (sometimes) compared to `estimate_gas` error `The execution failed due to an exception`, so we use prefer to use the `eth_call` response. The promise for estimate_gas is still executing and being logged by our global rejected promise handler.
This just cleans it up a little so it doesn't alert us on this error case, it is assumed we throw a much more informative error as `eth_call` and `estimate_gas` should fail in tandem.
=> Catch estimate gas error

src/handlers/swap_handlers.ts
When using the `swap/quote` endpoint, if `buyToken` and `sellToken` are the same, we return 4xx Validation Error with an informative reason.
We are returning 500 Internal Server Error which makes it seem like the API is broken
=> Change Internal Server Error to Validation Error

package.json, src/config.ts, yarn.lock
Adjust bridge slippage to 1%.
Upgrade Asset-swapper to account for transaction cost routing.
Set reasonable defaults by source.
=> Transaction cost routing

src/services/swap_service.ts
`869584cd000000000000000000000000aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa000000000000000000000000000000000000000000000000000000005e55dcdf`
```typescript
{
constant: true,
outputs: [],
name: 'ZeroExAPIAffiliate',
inputs: [{ name: 'affiliate', type: 'address' }, { name: 'timestamp', type: 'uint256' }],
payable: false,
stateMutability: 'view',
type: 'function',
}
```
`timestamp`: In Unix time seconds
=> Timestamp affiliate data

src/config.ts, src/constants.ts, src/services/swap_service.ts
`slippagePercentage` in AssetSwapper really is more of an over-buy percentage. So instead of requesting to sell 100 tokens, we request to sell 120 tokens. The history of this parameter predates Sampler and was to fetch MORE 0x orders than necessary, in the event that some were cancelled or filled. There would be "backup" orders to fill. 
Unfortunately this has a few issues:
* It is not guaranteed to fetch MORE orders (the same order could be for 200 tokens as an example)
* It is not guaranteed to fetch DISTINCT orders (the same maker could've cancelled ALL orders)
* It messes with gas estimation (you estimate against the first few orders succeeding, not against the first first orders failing and the last few orders filling)
* On large fills it can fetch a lot of orders
* A user adjusting …
=> Align slippage parameters

src/utils/mesh_client.ts
I'm having trouble with my local docker at the moment but this seems to be the cause. The validation code above is checking for undefined on `result` whereas we are then passing `results`.
Can someone test this out, or we can test it out on staging.
=> Fix typo in accessing property

src/config.ts
So we, err, can't forget to add the cost for a source.
=> Enforce Source fees with strict typing

.circleci/config.yml, package.json, src/config.ts, src/services/swap_service.ts, yarn.lock
This PR upgrades 0x API to the latest `AssetSwapper` (package is not released yet) and provides a path to add private liquidity providers to 0x API. Private liquidity providers can now be added to 0x API by setting the `LIQUIDITY_POOL_REGISTRY_ADDRESS` environment variable to the liquidity provider's registry contract.
=> Liquidity provider integration

package.json, src/config.ts, src/constants.ts, src/services/swap_service.ts, src/types.ts, yarn.lock
* Adds fallback path when 0x Native orders are used in the optimal path.
* Adds `guaranteedPrice` in the response now that we're potentially falling back with a path that has additional slippage. It will fill at this price (or better) or revert.
* Bumps the gas schedule to be more accurate with reality of filling via a bridge.
* Bumps default slippage to 3% during these volatile times.
* `gas` is now always returned as our faux estimate or a real estimate (whatever is largest)
Dev has 3%, 1.5% bridgeSlippage, maxFallbackSlippage
Production has 1% slippage and no fallback
You can observe the fallback path and increase in slippage to 3% has a significant effect in these volatile times.
Dev has 3%, 1.5% bridgeSlippage, maxFallbackSlippage
Staging has 1.5%, 1.5%
You can observe the fallback …
=> Fallback path

README.md
I think I found a typo in the documentation, so here's a fix.
=> Fix swap service launch command

README.md, src/handlers/swap_handlers.ts
Needs to find the value of `CurveUsdcDaiUsdt` i.e `Curve_USDC_DAI_USDT` as that is what is used internally in asset-swapper and returned via the API. 
`excludedSources=CurveUsdcDaiUsdt` was returning `['CurveUsdcDaiUsdt']` and `excludedSources=Curve_USDC_DAI_USDT` was returning `[]`. `Native/0x` and `Kyber` etc are fine as they don't have different key/values.
=> Fix excluded sources

src/services/orderbook_service.ts
```
diff --git a/src/services/orderbook_service.ts b/src/services/orderbook_service.ts
index 5dbc46b..355b486 100644
--- a/src/services/orderbook_service.ts
+++ b/src/services/orderbook_service.ts
@@ -31,10 +31,12 @@ export class OrderBookService {
assetDataA?: string,
assetDataB?: string,
): Promise<PaginatedCollection<AssetPairsItem>> {
+        console.time('order_fetch');
const signedOrderEntities = (await this._connection.manager.find(SignedOrderEntity)) as Array<
Required<SignedOrderEntity>
>;
-
+        console.timeEnd('order_fetch');
+        console.time('filtering');
const assetPairsItems: AssetPairsItem[] = signedOrderEntities
.map(orderUtils.deserializeOrder)
.map(orderUtils.signedOrderToAssetPair);
@@ -52,12 +54,17 @@ export class OrderBookService { …
```
=> Make /asset_pairs more efficien

src/utils/mesh_client.ts
Await using a `for of` instead of `forEach` which doesn't await.
=> Await results from Mesh validation

src/services/swap_service.ts
If a liquidity source is not utilized in swap quote, `sources` will return the liquidity provider with `proportion` set to zero. This will allow for easier understanding of the potential breakdown of liquidity when requesting a quote. 
Docs update: https://github.com/0xProject/website/pull/274
=> Add zeros for sources

src/constants.ts, src/errors.ts, src/handlers/swap_handlers.ts, src/services/swap_service.ts, src/utils/token_metadata_utils.ts
You can now unwrap and wrap between ETH and WETH by requesting a quote:
- `sellToken=WETH` and `buyToken=ETH` for unwrapping
- `sellToken=ETH` and `buyToken=WETH` for wrapping
Providing either `sellAmount` and `buyAmount`  will give the same behavior because the "rate" between ETH<>WETH is always 1:1.
I have opted out of making the changes to support unwrapping and wrapping in asset-swapper because it seems out of scope and requires larger changes to AS that seem rather costly for such a feature.
- AS relies on token addresses and asset data to identify assets; with that we would need to introduce some ability to identity `ETH` between `WETH` to `SwapQuoter`'s interface. This would require a large change to AS.
- Behind the scenes, SwapQuoter will need to do quite a bit of work to skip …
=> Handle WETH and ETH unwrapping/wrapping  with swap quote

test/app_test.ts, tsconfig.json
Expands RFQ-T testing
* Test for not returning an order when maker does _not_ have allowances set
* Test for `skipValidation` being default set to `false`
* Test for `skipValidation` behaving as expected when set to `true`
* Test for a bad API key being sent in
=> RFQT: More tests

src/app.ts, src/index.ts, src/logger.ts, src/runners/http_service_runner.ts, src/runners/http_sra_service_runner.ts, src/runners/http_staking_service_runner.ts, src/runners/http_swap_service_runner.ts, src/runners/order_watcher_service_runner.ts, src/utils/mesh_utils.ts, src/utils/order_utils.ts
`BigNumber` fields in `SignedOrder` were not being cast and instead were being passed around as `number` primitives, leading to failures when calling `.gt()`. This PR calls `>` instead of `.gt()`. 
Also start logging `error.stack` instead of `error` everywhere. Logging `error` shows up as `Error [[Object object]]` whereas `error.stack` is informative.
successful deploy and OrderWatcherService sync logs here: https://kibana.mesh.0x.org/goto/05c2f0125ec0772142300e7d7cc3f69d
=> Fix expired order filter, better error logging

package.json, yarn.lock
Adds additional sources when `buyAmount` is used as an API parameter. Previously Kyber and Curve were not used. 
Now Curve has support for exact sampling of buy amounts. For Kyber we approximate with a 5bps tolerance.
=> Extended buyAmount sources

src/utils/service_utils.ts
When `uint8` is used as an output it is decoded as `number` not `BigNumber`
=> uint8 is decoded as number

src/utils/axios_utils.ts, src/utils/mesh_client.ts
Change retry-axios to only apply to an explicit instance, instead of being on the global Axios object.
This fixes the code so RFQT requests are not retried
=> Make axios retryable only when desired

src/handlers/signer_handlers.ts
Change from returning 502 to 403 (FORBIDDEN) to elucidate the request contained valid data and was understood by the server, but the server is refusing action. The body returns the unsigned Ethereum txn.
=> Use 403 instead of 503 if /submit can't submit the meta-txn

src/handlers/signer_handlers.ts
We accidentally return the nonce with the unsigned Ethereum txn when we shouldn't.
=> [meta-txn] Remove nonce

src/queries/staking_queries.ts, src/types.ts, src/utils/staking_utils.ts
Removed total protocol fees from current epoch query to improve performance.
Query runtime on Hashalytics:
~180ms -> ~150ms
Testing:
=> Removed totalProtocolFeesGeneratedInEth

package.json, test/app_test.ts, yarn.lock
https://github.com/0xProject/0x-monorepo/pull/2565
Native Orders which are perfectly sized to the target amount should not be penalised more than a larger order.
=> fix: Clip Native Order penalty

src/middleware/request_logger.ts
We feel comfortable having this API key in our logs, and it's very useful to have in Kibana.
=> fix: Log 0x api key

package.json, src/services/swap_service.ts, yarn.lock
Asset-swapper cannot currently determine that the taker (if provided) has the ability to pay the taker fee in the maker asset. This is guaranteed by the balance, but is not guaranteed by the allowance of the taker.
Also updates the Kovan ERC20BridgeSampler address. https://github.com/0xProject/0x-monorepo/pull/2570
=> fix: Prune Taker fees in Maker asset

src/errors.ts, src/handlers/meta_transaction_handlers.ts, src/handlers/swap_handlers.ts
If slippage percentage is > 1 (100%), throw an informative validation error.
The confusion over orders of magnitude (0.02 instead of 2 to mean "2%") has tripped us up a couple of times already.
=> fix: validate slippagePercentage <= 1

src/handlers/meta_transaction_handlers.ts, src/services/meta_transaction_service.ts, src/types.ts
This PR adds support for RFQT quotes via the meta-txn endpoints. More specifically it adds API Keys to meta-txn /price & /quote endpoints and pass RFQT opts into Asset-swapper in order for RFQT orders to surface.
=> feat: Support RFQT via Meta-txn Endpoints

package.json, src/config.ts, src/constants.ts, src/handlers/swap_handlers.ts, src/services/swap_service.ts, src/types.ts, test/app_test.ts, test/utils/deployment.ts, test/utils/mocks.ts, yarn.lock
Lots of tasks that needed doing after the initial implementation of RFQ-T. I recommend reviewing commit by commit.
Depends on https://github.com/0xProject/0x-monorepo/pull/2574
-   [x] Test on staging, exercising the new `RFQT_MAKER_ASSET_OFFERINGS` environment variable scheme.
-   [x] Re-pin asset-swapper to monorepo `development`-branch commit, after https://github.com/0xProject/0x-monorepo/pull/2574 merges. (Currently this is pinned to a commit in that PR's branch).
=> feat: RFQ-T follow-ups

CHANGELOG.md, package.json, src/handlers/swap_handlers.ts, yarn.lock
Updates logging to support the operational monitoring of RFQ-T usage.
Re-pins to [an updated `asset-swapper`](https://github.com/0xProject/0x-monorepo/pull/2581) with similar changes.
View new logging in output of existing (mocha) tests.  Below are some examples from the latest CI run of this PR.  For each text log entry I've included a nice visual rendering to go with it.
---
`{"level":"info","time":1589240068300,"pid":5145,"hostname":"e6c519a5c290","firmQuoteServed":{"taker":"0x6ecbe1db9ef729cbe972c83fb886247691fb6beb","apiKey":"koolApiKey1","buyToken":"ZRX","sellToken":"WETH","sellAmount":"100000000000000000","makers":["0x5409ED021D9299bf6814279A6A1411A7e866A631"]},"v":1}`
---
`{"level":"info","time":1589240069170,"pid":5145,"hostname":"e6c519a5c290","indicativeQuoteServed":{"taker":"0x …
=> feat: Improve RFQ-T logging

src/queries/staking_queries.ts
Edited the staking query for next epoch to return a better approximate value.
Tested on hashalytics.
=> fix: made the estimated starting block for the next epoch more accurate

src/services/meta_transaction_service.ts
This PR removes the check for `status` inside of `_waitUntilTxHashAsync` to not run into a race condition where the status was updated to `Included` or `Mempool` quicker than the polling loop.
Run `yarn integration-test`
=> fix: remove check for status from _waitUntilTxHashAsync procedure

src/handlers/meta_transaction_handlers.ts, src/handlers/swap_handlers.ts, src/services/meta_transaction_service.ts, src/types.ts, test/meta_transaction_test.ts, test/utils/mocks.ts
This fixes #227.
When integrating with the `/price` endpoints I noticed that the data returned back is very sparse compared to the quote endpoint. I also noticed that two endpoints return different data, so I tried to unify to the point it makes sense.
For us, it would be very helpful to be able to derive the pair from the response data so we don't have to keep track of that locally in the global state.
**TODO:**
-   [X] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. **Website Documentation PR:** 0xProject/website#298
-   [X] Prefix PR title with `[WIP]` if necessary.
-   [X] Add tests to cover changes as needed.
=> fix: unify the response data from /swap/v0/price and /meta_transaction/v0/price

src/constants.ts
=> feat: lower default slippage percentage to 1%

package.json, yarn.lock
To pick up a small fix for logging RFQ-T maker endpoint response error codes. 
This is the monorepo commit being pinned to: https://github.com/0xProject/0x-monorepo/commit/98a99d96aab15623188661568785b5354e66172a
At the time of this writing (9am PT, May 28) that's the latest monorepo commit.
This change has been verified on staging.  However, I did not verify the actual case being corrected (the error response code handling from the maker endpoint), because it was not readily apparent to me how to simulate that.  But what I _did_ test was that existing functionality is holding together okay.  To do that I requested a few RFQ-T quotes, and also ran the Assertible smoke tests.
=> fix: Re-pin asset-swapper to latest monorepo commit

src/handlers/meta_transaction_handlers.ts, src/types.ts
Add ethereum transaction status to the response of `/status/:refHash`
=> feat: return ethereum transaction status in the response from metatxn status

src/queries/staking_queries.ts, src/services/staking_data_service.ts, src/types.ts, src/utils/staking_utils.ts
Added a new field to the `pools` and `pools/<id>` endpoint called `avgMemberRewardEthPerZrx`. It provides the average member reward over the last 3 epochs divided by the average member stake. 
Testing:
=> feat: added rewards per ZRX to pools endpoint

package.json, src/config.ts, test/meta_transaction_test.ts, test/rfqt_test.ts, test/swap_test.ts, test/utils/deployment.ts, test/utils/mocks.ts, yarn.lock
Add support for UniswapV2
Using UniswapV2Router01 contract through asset-swapper.
Add `Uniswap_V2` and `Uniswap_V2_ETH` as new sources in `excludedSources` parameter. No other changes.
Unit tests should all still work.
-   [x] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. **Website Documentation PR:** https://github.com/0xProject/website/pull/305
=> feat: Add support for UniswapV2 and MultiBridge

src/services/swap_service.ts, test/rfqt_test.ts, test/swap_test.ts
=> fix: Disable quote validation temporarily

src/constants.ts, src/services/meta_transaction_service.ts, src/services/swap_service.ts, test/rfqt_test.ts, test/swap_test.ts
Geth shipped a breaking change which did the following.
1.  Removed the "bug" which allowed the caller to have `value` irrespective of their ETH balance
2. Set the gas limit to MaxUint64 if not supplied
These two combination results in an insufficient funds as not even Vitalik has enough funds for 50 gwei @ MaxUint64 gas limit.
As a result we either need to drop (or lower) gas price to 1 wei, resulting in the user requiring 18 ETH for validation. We want to validate the gas price and protocol fee, so we cannot drop the gas price entirely. So this is out.
So we need to either fix the gas limit to something reasonable in the case we're performing a validation (eth call with ?? gas). Or we perform the Estimate gas first then the `eth_call`, unable to parallelize.
In `/swap/v0/quote` we have …
=> fix: validation gas limit

package.json, test/rfqt_test.ts, yarn.lock
Uses a new asset-swapper, which has support for the [maker endpoint's renamed taker request parameters](https://github.com/0xProject/quote-server/pull/5).
-   [x] Re-pin asset-swapper to a monorepo `development` commit rather than a PR branch commit, once https://github.com/0xProject/0x-monorepo/pull/2582 has been merged.
=> feat: support renamed parameters in RFQT maker endpoint

.github/workflows/ci-build.yml, src/services/swap_service.ts
=> fix: remove undefined extension opts

src/config.ts, src/services/meta_transaction_service.ts, src/services/swap_service.ts, src/types.ts
We noticed that RFQT latency on `api.0x.org` can be too high at times and may cause downstream latency to our customers, so we are going to cap HTTP RFQT timeouts to 600ms.  This PR sets the `makerEndpointMaxResponseTimeMs` parameter that can be optionally specified in `RfqtRequestOpts`, and that defaults to 1 second. We are intentionally enforcing this parameter to be `600`.
⚠️ We noticed that 0x API passes to Asset Swapper some parameters that do not exist anymore. More precisely:
- `skipBuyRequests` is an old relic of when our RFQT bot only supported sell requests. skipBuyRequests is not used at all by AssetSwapper, since it’s not present in [RfqtRequestOpts](https://github.com/0xProject/0x-monorepo/blob/85ca926fd012d9233c01a0a2a58e8709d5dabe32/packages/asset-swapper/src/types.ts#L202). …
=> fix: Changes latency to be capped at 600ms, added some extra typing

package.json, src/config.ts, src/ormconfig.ts, src/services/meta_transaction_service.ts, src/services/swap_service.ts, yarn.lock
https://github.com/0xProject/0x-monorepo/pull/2637
=> feat: Update protocol fee to 70k. Yield to event loop in path optimizer

src/config.ts, src/constants.ts, src/handlers/healthcheck_handlers.ts, src/routers/healthcheck_router.ts, src/runners/http_meta_transaction_service_runner.ts, src/runners/http_service_runner.ts, src/runners/http_sra_service_runner.ts, src/runners/http_staking_service_runner.ts, src/runners/http_swap_service_runner.ts, src/runners/utils.ts, src/services/healthcheck_service.ts, src/types.ts, test/utils/deployment.ts
This PR adds a `createDefaultServer` function to be used across all HTTP runners which prepares a `http.Server` with:
- Header timeouts `server.keepAliveTimeout` &  `server.headersTimeout`
- Healthcheck service exposed at `/healthz`
- Graceful shutdown through [server.close](https://nodejs.org/api/http.html#http_server_close_callback)
- Adds common middleware: `requestLogger`, `cors`, `bodyParser`
This PR has been tested on staging, however we can still unit test the graceful shutdown:
=> feat: Graceful Shutdowns

package.json, src/config.ts, src/constants.ts, src/handlers/swap_handlers.ts, src/routers/swap_router.ts, src/services/swap_service.ts, src/types.ts, src/utils/market_depth_utils.ts, test/market_depth_test.ts, yarn.lock
requires: https://github.com/0xProject/0x-monorepo/pull/2641
includes: Quicker Path Finding https://github.com/0xProject/0x-monorepo/pull/2640
Returns bucketed pricing for all sources.
```
http://localhost:3000/swap/v0/depth?buyToken=USDC&sellToken=DAI&sellAmount=10000e18&numSamples=10&sampleDistributionBase=1
```
```json
{
"asks": {
"depth": [
{
"price": "0.00315546105784902",
"bucket": 0,
"bucketTotal": "0",
"sources": {
"Native": "0",
"Uniswap": "0",
"Uniswap_V2": "0",
"Eth2Dai": "0",
"Kyber": "0",
"Curve": "0",
"LiquidityProvider": "0",
"MultiBridge": "0",
"Balancer": "0"
},
"cumulative": "0"
},
{
"price": "0.00312390644727053",
"bucket": 1,
"bucketTotal": "100524109029123426136",
"sources": {
"Uniswap": "9381248534278317553",
"Kyber": "31432971221060620000",
"Native": …
```
=> feat: Depth Chart API endpoint

package.json, src/config.ts, yarn.lock
https://github.com/0xProject/0x-monorepo/pull/2644
=> fix: Kovan ERC20BridgeSampler

package.json, yarn.lock
https://github.com/0xProject/0x-monorepo/pull/2660
Certain edgecase scenarios can exist when the liquidity only lives on 0x Native and an `ethToMakerRate` cannot be determined on-chain.
Without an `ethToMakerRate` all fills are considered free and many native orders can be filled costing a pretty penny.
[Sell - pause-perpetual-cave](https://metabase.0xproject.com/dashboard/139?run_id=pause-perpetual-cave)
[Buy - facilitate-tender-number](https://metabase.0xproject.com/dashboard/139?run_id=facilitate-tender-number)
[Staging v Prod](https://metabase.0xproject.com/dashboard/139?run_id=grate-precious-zinc)
**Previous**
```json
{
"price": "4.000561",
"guaranteedPrice": "4",
"to": "0x61935cbdd02287b511119ddb11aeb42f1593b7ef",
"value": "21000000000000000",
"gas": "540000",
"estimatedGas": …
```
=> feat: ethToInputRate cost routing

src/ormconfig.ts, src/services/swap_service.ts, src/token_metadatas_for_networks.ts
=> fix: lower db pool connections

package.json, src/handlers/swap_handlers.ts, src/services/swap_service.ts, test/rfqt_test.ts, yarn.lock
Changed RFQ-T enablement constraints such that a `takerAddress` query parameter is no longer required when coming through the `/price` endpoint.
Use [Matcha on staging](https://api-staging.matcha.xyz/markets/DAI/USDC), and don't connect your wallet, and request some pricing, and check the API staging logs to ensure that RFQ-T liquidity was accessed.
-   [x] Implement.
-   [x] Test manually on staging.
-   [x] Merge [monorepo PR](https://github.com/0xProject/0x-monorepo/pull/2684) and re-pin the dependency herein to the `development` branch.
=> feat: Allow indicative RFQ-T quotes without takerAddress

package.json, src/services/meta_transaction_service.ts, src/services/swap_service.ts, yarn.lock
Paired with https://github.com/0xProject/0x-monorepo/pull/2696
* Turns on quote reports _only_ for RFQT firm quotes
* Quote reports are much more optimized by looking up taker amount by signature instead of orderHash ( https://github.com/0xProject/0x-monorepo/pull/2696 )
=> feat: turn back on quote reports for firm quotes

src/constants.ts, src/services/swap_service.ts
* Added a buffer around eth_estimateGas when it is higher than our fauxEstimate
* Kyber should now also be deterministic as we always go through a specific reserve
=> fix: Add 10% to eth_estimateGas

src/queries/staking_queries.ts
Alters the average rewards query to ensure no division by zero error.
=> fix: Avoid divide by 0 in the average rewards query

src/utils/parse_utils.ts
Small bug with `Server Error` when `excludedSources=0x,Mesh`. [example request](https://api.matcha.0x.org/swap/v1/price?affiliateAddress=0x86003b044f70dac0abc80ac8957305b6370893ed&buyToken=ETH&excludedSources=0x,Mesh&includePriceComparisons=false&sellAmount=1000000000000000000&sellToken=0x6b175474e89094c44da98b954eedeac495271d0f&skipValidation=false&slippagePercentage=0.01)
[This line in parse utils](https://github.com/0xProject/0x-api/blob/master/src/utils/parse_utils.ts#L54-L59) sets `nativeExclusivelyRFQT=true` when excluded sources includes `Mesh`:
```
if (excludedIds.length > 0) {
return {
excludedSources: parseUtils.parseStringArrForERC20BridgeSources(excludedIds),
includedSources: [],
// Exclude open orderbook if 'Mesh' is excluded.
nativeExclusivelyRFQT: …
```
=> Fix bug when excludedSources=Native,Mesh

package.json, test/meta_transaction_test.ts, yarn.lock
Re-pins to https://github.com/0xProject/protocol/commit/8de0282d92895f9dd5796582cad2c66b4f0c1c99
And adapts to a new version of `jsonschema` that gets pulled in resulting from that.
=> chore: re-pin asset-swapper to mainline protocol

src/handlers/meta_transaction_handlers.ts, src/handlers/swap_handlers.ts, src/services/meta_transaction_service.ts, src/services/swap_service.ts, src/token_metadatas_for_networks.ts, src/utils/token_metadata_utils.ts, test/constants.ts, test/meta_transaction_test.ts, test/swap_test.ts
This adds support for passing ETH as `buyToken` or `sellToken` via symbol and our fake ETH token address (`0xeee...`). `buyTokenAddress` and `sellTokenAddress` address is now correct reflecting ETH in the response, even with the trade being handled as a WETH trade + wrap/unwrap internally.
The meta transaction endpoints now correctly support buying and receiving ETH with a metatx.
-   [X] Add tests to cover changes as needed.
=> fix: Fix support for passing ETH as buyToken and sellToken

package.json, src/config.ts, src/services/swap_service.ts, yarn.lock
Adds a feature flag called PRICE_AWARE_RFQ_ENABLED that can be used to enable the Price-aware RFQ service. The flag is off by default. Most likely this PR will need a new deploy once https://github.com/0xProject/protocol/pull/13 is merged
=> fix: [WIP] Adds PRICE_AWARE_RFQ_ENABLED environment

package.json, yarn.lock
Upgrades Asset Swapper to support the new `comparisonPrice` logging
=> fix: upgrades asset swapper

src/services/meta_transaction_service.ts
This fixes #124. If the hex values are intentional feel free to close this PR. I just found it a bit odd that this endpoint returns these values as hex whereas other endpoints return them as decimals.
-   [X] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. **Website Documentation PR:** 0xProject/website#303
=> fix(metatx): don't return hexadecimal values in partial tx

src/handlers/sra_handlers.ts, src/services/orderbook_service.ts, src/types.ts, test/orderbook_service_test.ts
This PR converts the query param from string to boolean and allows to fetch persistent orders properly.
=> fix: fetch persistent orders

src/services/swap_service.ts, src/utils/price_comparison_utils.ts, test/price_comparison_utils_test.ts
Price decimals should match maker asset for sell quotes and
taker asset for buy quotes
-   [x] Test changes on the staging environment with [Matcha API Staging](https://api-staging.matcha.xyz).
-   [x] SRA/Limit orders
-   [x] Swap endpoints
-   [x] Meta transaction endpoints
-   [x] Depth charts
=> fix: use correct decimal precision for price and price comparisons

src/entities/PersistentSignedOrderEntity.ts, src/entities/SignedOrderEntity.ts, test/orderbook_service_test.ts, test/sra_test.ts
- adding `createdAt` to SignedOrders table. 
- previously added `createdAt` to PersistentSignedOrders table (https://github.com/0xProject/0x-api/pull/443) but since we only return PersistentSignedOrders entities for expired/inactive orders, I had to add `createdAt` to the SignedOrders table for active orders. 
For more information see `0x API …
=> fix: add createdAt to SignedOrders table

src/handlers/sra_handlers.ts, src/schemas/sra_get_orders_request_schema.json, src/services/orderbook_service.ts, src/types.ts, src/utils/order_utils.ts, src/utils/pagination_utils.ts, src/utils/parse_utils.ts, tslint.json
Limits by `perPage` and offsets by by `page * perPage` in the db rather then in memory. It does mean that some of the other filters are less accurate (`traderAddress, makerAssetAddress, takerAssetAddress, makerAssetProxyId, takerAssetProxyId`) but I believe these are rarely used.
**no filters**
```
hey -c 1 -n 30 'https://staging.api.0x.org/sra/v3/orders'           feat/fetch-token-and-duration*
Summary:
Total:	4.8126 secs
Slowest:	0.6201 secs
Fastest:	0.1234 secs
Average:	0.1604 secs
Requests/sec:	6.2337
Total data:	603494 bytes
Size/request:	20116 bytes
Response time histogram:
0.123 [1]	|■■
0.173 [26]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
0.223 [1]	|■■
0.272 [0]	|
0.322 [0]	|
0.372 [0]	|
0.421 [1]	|■■
0.471 [0]	|
0.521 [0]	|
0.570 [0]	|
0.620 [1]	|■■
```
```
hey -c 1 -n 30 …
```
=> chore: Move pagination to db for heavier queries

src/services/swap_service.ts, test/swap_test.ts
Changes the default allowance target value to the new target (0x Exchange Proxy).
[Sims](https://metabase.spaceship.0x.org/dashboard/139?run_id=new-allowance-target&adjusted_amount_bought_win_tolerance__bps_=0.5)
=> chore: Change allowance target to 0xdef1

src/services/swap_service.ts, src/utils/utils.ts
Requires https://github.com/0xProject/protocol/pull/151
Previously a single `swap/v1/quote` request would perform the following:  
1. Sample (`eth_call`)
2. Gas estimation (`eth_estimateGas`)
3. Validation (`eth_call` using the gas + data to surface any revert data)
This resulted in 3 RPC calls, we now get the gas estimation in an `eth_call` by making use of Geth overrides. We add in the base gas cost and the per byte call data cost.
-   [ ] …
=> feat: Perform gas estimation with a single call

src/middleware/address_normalizer.ts, src/utils/address_utils.ts, src/utils/mesh_utils.ts
There is an inconsistency in the address casing of v4 order data received from Mesh, it seems like query responses return strictly lower case addresses, whereas the subscription order event updates can return checksummed addresses. This lead to some issues with checksummed addresses temporarily getting into the DB when inserted from an `ADDED` event, but then lowercased when API was restarted and it does a full sync query to Mesh.
-   [ ] …
=> fix: lowercase addresses in order update event data received from Mesh

src/config.ts, src/schemas/api_key_schema.json, src/schemas/index.ts, test/parse_utils_test.ts
This PR creates a new API key structure, where every API key can have multiple "features" enabled. The feature is built so that it will fallback on the existing key structure in order to support a phased migration of the configurations.
```json
{
"foo": {"rfqm": false, "rfqt": true, "plp": true, "label": "Foo key" }, 
"bar": {"rfqm": false, "rfqt": true, "plp": false, "label": "Bar key" }, 
"baz": {"rfqm": false, "rfqt": false, "plp": true, "label": "Baz key" }, 
"barf": {"rfqm": true, "rfqt": false, "plp": false, "label": "Barf key" }, 
}
```
=> fix: New API key structure

src/services/order_watcher_service.ts, src/services/orderbook_service.ts
This change prevents 0xAPI to send a request to Mesh with no orders, saving on roundtrip time as well as on uneccessary handling as v11.2 will return an error.
SRA was sending empty orders because of  :
```
const pinResult = await orderUtils.splitOrdersByPinningAsync(signedOrders);
await Promise.all([
this._orderBook.addOrdersAsync(pinResult.pin, true),
this._orderBook.addOrdersAsync(pinResult.doNotPin, false),
]);
```
in https://github.com/0xProject/0x-api/blob/master/src/handlers/sra_handlers.ts#L108
-   [ ] Test changes on the staging environment …
=> fix: avoid making a post request to mesh with no orders

src/utils/price_comparison_utils.ts, test/price_comparison_utils_test.ts
This fixes the issue with incorrect gas estimates in price comparisons. We should hold off with shipping this until we've figured how to migrate and correct the historical data we already have.
=> fix: price comparisons not accounting for tx base gas & quote gas buffer

src/handlers/rfqm_handlers.ts, test/rfqm_test.ts
Right now, returning a 404 if liquidity is unavailable. Change this to a boolean value `liquidityAvailable`
Tests updated
=> feat: return a liquidityAvailable flag on rfqm /price and /quote endpoints

migrations/1625865121323-AddRfqmAffiliateAddressField.ts, src/entities/RfqmJobEntity.ts, src/entities/RfqmQuoteEntity.ts, src/handlers/rfqm_handlers.ts, src/services/rfqm_service.ts, src/utils/rfq_blockchain_utils.ts, test/rfq_blockchain_utils_test.ts, test/rfqm_db_test.ts, test/rfqm_test.ts
The goal is to make RFQM calldata consistent with 0x API calldata by encoding 'affiliate data' into the transaction data.
There are existing tests for RFQ blockchain utils and the serviceUtils.attributeCallData().
Integration tests are modified to test that the affiliate address is properly saved in the database.
For more information see `0x …
=> feat: add affiliateAddress to rfqm calldata

src/config.ts, src/handlers/swap_handlers.ts, test/config_test.ts, test/test_env
Send the integrator IDs instead of API keys when `/swap/rfq/registry` is queried.
`yarn test` it out
=> fix: Send integrator IDs for /swap/rfq/registry

src/rpc_subprovider.ts
Update the deployment config to include
```
ENABLE_PROMETHEUS_METRICS=true
PROMETHEUS_PORT=8080
```
=> chore: Enable Prometheus metrics on RPC subprovider

package.json, tsconfig.json, yarn.lock
Upgrade `typescript` dependency from `4.3.x` to `4.4.x`. With no `tsconfig` change, this minor version breaks the 0x API build by [changing the type of `catch` variables from `any` to `unknown`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#defaulting-to-the-unknown-type-in-catch-variables---useunknownincatchvariables). While we should consider modifying `catch` blocks to test for `instanceof Error`, the extra safety probably isn't worth the effort.
Modify typescript configuration to restore previous default behavior.
=> chore: Bump typescript to 4.4.x

src/utils/rfqm_health_check.ts
Closes MKR-163
Add Prometheus counters to the RFQM health check.
After the health check runs, look at each issue and increment a Prometheus counter with the lablels `<status>, <label>`, for instance `degraded, worker balance`.
=> feat: Add prometheus counters to RFQM health check

src/utils/rfqm_health_check.ts, test/utils/rfqm_health_check_test.ts
Aligns the health check with the < 2 workers with 0.1 ETH balance alert.
=> feat: Update rfqm balance degraded threshold to align with current alerting

src/services/rfqm_service.ts, src/utils/rfqm_db_utils.ts, test/services/rfqm_service_test.ts
Closes MKR-185
We've seen issues where a taker submits multiple trades for the same token in rapid sequence, likely because they don't understand the first trade is being processed.
Update the submit logic to make sure that the RFQM system isn't currently processing a trade for the taker with the same token as a new trade.
=> fix: Prevent RFQM from accepting a trade when a trade with the same taker & taker token is pending

package.json, yarn.lock
Bumps `asset-swapper` to latest version which includes the new `@0x/neon-router` behind a feature toggle.
If `process.env.RUST_ROUTER` is set to anything `asset-swapper` will use the `@0x/neon-router` library, if not it will use our current router.
=> chore: bump asset-swaper to neon-router enabled version (feature toggled)

src/logger.ts
Have you noticed that annoying message throughout the API outputs: `[PINODEP001] Warning: useLevelLabels is deprecated, use the formatters.level option instead`? Time to fix it.
Update `pino` logger with the new formatting. This shouldn't change the output at all, just get rid of the warning. See https://github.com/pinojs/pino/issues/848#issuecomment-642768553.
- …
=> fix: Fix pino useLevelLabels warning

src/handlers/swap_handlers.ts, src/services/swap_service.ts
Presently, we hardcode `skipValidation: true`  in every `/price` request. This means we do not have accurate gas estimates on /price. As we will be using the gasEstimate to compare the all-in price of gasless swaps vs traditional swaps, it's important we get the gas estimate as close to correct as possible.
After speaking w/ @dekz - the reason we do not produce high fidelity gas estimates on `/price` is that we cannot call `eth_estimateGas` when RFQ indicative quotes are present. Thus, a large percentage of `/price` requests would fail when we estimate gas.
However, when RFQ is not present, we _do_ have the ability to estimate.
This change removes the hardcoding of skipValidation on price, and uses the sources to determine if we can estimate gas. It should do the following:
- Firm quotes …
=> fix: get better gas estimates on /price

src/handlers/swap_handlers.ts
=> fix: revert gas estimations on /price endpoints due to breaking change

src/app.ts
Currently RFQt only support Mainnet so the PairsManger, which queries DB to refresh in memory pairs, should only be initialized and used in Mainnet pods.
=> fix: avoid creating a PairsManager for layer2 chains

src/handlers/swap_handlers.ts, src/services/meta_transaction_service.ts, src/services/swap_service.ts, src/types.ts, test/swap_test.ts
Previously, in #804 - a change was introduced to call `eth_estimateGas` when we had the appropriate calldata to do so. However, this change did not take into account that sometimes this rpc call could fail for balance and allowance reasons. 
If the taker did not have enough balance, they would get an error that looks like this:
```
{
"code": 105,
"reason": "Error",
"values": {
"message": "ERC20: transfer amount exceeds allowance"
}
}
```
This effectively broke any integrations that were relying on the `/price` to always work (even if the taker could not fill the order)
This change provides error handling around such a scenario.
However, we want to preserve this behavior on the `/quote` endpoint, and hence, bubble the error up if seen on a firm quote
Added a new test for `/price` endpoint …
=> fix: /price endpoint does not fail on eth_gasEstimate error

src/config.ts, src/handlers/swap_handlers.ts, src/services/swap_service.ts, src/types.ts, src/utils/slippage_model_manager.ts, test/test_env, test/utils/slippage_model_manager_test.ts
Fix a few issues of `SlippageModelManager` according to recent discussion:
* `expectedSlippage` shall be `null` for trades below $10k in volume
* `expectedSlippage` shall not exceed the max slippage threshold set by the end-user
* `expectedSlippage` shall be `null` for unsupported pairs
* `expectedSlippage` shall be `null` for unsupported sources
* for trades spanning across multiple sources, the overall `expectedSlippage` shall be `null` if `expectedSlippage` of any individual source is `null`.
Also according to Jacob's comment, remove derived fields `expectedBuyAmount` and `expectedSellAmount`.
Unit test added to cover `SlippageModelManager`.
- …
=> fix: slippage model issues

src/config.ts, src/utils/slippage_model_manager.ts, test/utils/slippage_model_manager_test.ts
* Treat 0x (Native) source's slippage as 0 in `SlippageModelManager`
* Remove $10k usd threshold.
* Return 0 slippage if the slippage model predicts a positive slippage.
=> feat: Modify `SlippageModelManager` to handle native source and remove $10k usd threshold [TKR-461, MKR-513]

tsconfig.json
* `@0x/asset-swapper` uses generated wrappers which have unused variables
With `noUnusedLocals` enabled, the codebase won't compile.
* In short-term, `noUnusedLocals` can be disabled.
* Later, the same issue can be caught using eslint rule while excluding
generated files (or once generated-wrappers are removed, the rule can be
re-enabled).
For …
=> chore: Disable `noUnusedLocals` prior to asset-swapper migration [TKR-484]

src/config.ts, src/handlers/swap_handlers.ts, src/services/meta_transaction_service.ts, src/services/swap_service.ts, src/services/transaction_watcher_signer_service.ts, src/types.ts, tslint.json
* Disable `max-file-line-count` prior to `assest-swapper` migration to avoid lint error issues. 
* Remove references to `max-file-line-count`
=> chore: Disable `max-file-line-count` tslint rule and remove its references [TKR-484]

package.json, yarn.lock
typescript version upgrade introduced a regression when the server is run with `ts-node`. Upgrading `ts-node` fixes the issue. 
```
ts.Debug.assert(typeof typeReferenceDirectiveName === "string", "Non-string value passed to `ts.resolveTypeReferen
ceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is pr
obably not a problem in TS itself.");
```
-   [ ] Swap …
=> fix: Upgrade ts-node to fix an issue introduced in typescript version upgrade

src/config.ts
* The default excluded sources is everything except `NativeSource` which is unlikely to be desired value for a new chain. 
It would be less error-prone to fail fast and require excluded sources to be manually specified for a new chain.
=> chore: Require `EXCLUDED_SOURCES` to be manually updated for a new chain

src/asset-swapper/utils/market_operation_utils/constants.ts, src/services/meta_transaction_service.ts
The old method was finding the symbol for 'weth' no matter what the chain. This is causing the wrong output token in metatransactions that should be an unwrap to MATIC.
=> fix: Use native fee token map to find wrapped native token

package.json, yarn.lock
`Rfq` must be 2 and `Otc` must be 3 to mathch the enum order of `FillQuoteTransformer.OrderType`
=> fix: Upgrade @0x/protocol-utils which had an incorrect version of `FillQuoteTransformer.OrderType`

contracts/src/UniswapV3Sampler.sol
* It is not sufficient to only check the first pool of a pool path
=> fix: Fix valid pool path check logic in `UniswapV3Sampler`

src/asset-swapper/utils/market_operation_utils/pools_cache/balancer_pools_cache.ts
`parsePoolData` can return an empty list. Unless they are filtered out, an `undefined` is populated in the pool cache and will cause a runtime error for quote of tokens that are associated with `undefined` pool cache.
=> fix: Skip bad pool data in Balancer v1 cache [TKR-627]

test/orderbook_service_test.ts
The top level tests (`test/*_test.ts`) were re-enabled in #1055. The tests passed initially but it started failing after it was merged. Skip flaky tests so that CI works properly. 
=> fix: Skip `ran getOrdersAsync test cases` in `orderbook_service_test.ts` [TKR-651]

src/asset-swapper/utils/market_operation_utils/identity_fill_adjustor.ts, src/asset-swapper/utils/market_operation_utils/path_optimizer.ts, src/asset-swapper/utils/market_operation_utils/types.ts, src/utils/slippage_model_fill_adjustor.ts
The parameter  `inputAmount` of `adjustFills` is never used. 
=> chore: Remove `inputAmount` from `FillAdjustor::adjustFills` [TKR-623]

src/asset-swapper/utils/market_operation_utils/path_optimizer.ts
* Two-hop `DexSample` may have an empty fill data when sampling was reverted.
* This logic was mistakenly removed in PR 1063 [0].
[0] https://github.com/0xProject/0x-api/pull/1063
=> fix: Restore invalid two hop `DexSample` filtering logic

src/asset-swapper/index.ts, src/asset-swapper/quote_consumers/exchange_proxy_swap_quote_consumer.ts, src/asset-swapper/quote_consumers/quote_consumer_utils.ts, src/asset-swapper/swap_quoter.ts, src/asset-swapper/types.ts, src/asset-swapper/utils/market_operation_utils/bridge_source_utils.ts, src/asset-swapper/utils/market_operation_utils/comparison_price.ts, src/asset-swapper/utils/market_operation_utils/constants.ts, src/asset-swapper/utils/market_operation_utils/fills.ts, src/asset-swapper/utils/market_operation_utils/identity_fill_adjustor.ts, src/asset-swapper/utils/market_operation_utils/index.ts, src/asset-swapper/utils/market_operation_utils/orders.ts, src/asset-swapper/utils/market_operation_utils/path.ts, src/asset-swapper/utils/market_operation_utils/path_optimizer.ts, src/asset-swapper/utils/market_operation_utils/sampler_contract_operation.ts, src/asset-swapper/utils/market_operation_utils/sampler_no_operation.ts, src/asset-swapper/utils/market_operation_utils/sampler_operations.ts, src/asset-swapper/utils/market_operation_utils/source_filters.ts, src/asset-swapper/utils/market_operation_utils/types.ts, src/asset-swapper/utils/quote_report_generator.ts, src/asset-swapper/utils/quote_simulation.ts, test/asset-swapper/comparison_price_test.ts, test/asset-swapper/dex_sampler_test.ts, test/asset-swapper/exchange_proxy_swap_quote_consumer_test.ts, test/asset-swapper/market_operation_utils_test.ts, test/asset-swapper/quote_report_generator_test.ts, test/asset-swapper/quote_simulation_test.ts, test/asset-swapper/utils/market_operations_utils/path_optimizer_test.ts
started working on removing circular deps in asset-swapper. I moved a lot of things up from inside asset-swapper/market-operations up to asset-swapper/types
=> chore: circular deps part 2

src/asset-swapper/swap_quoter.ts, src/asset-swapper/types.ts, src/asset-swapper/utils/market_operation_utils/constants.ts, src/asset-swapper/utils/quote_simulation.ts, test/asset-swapper/market_operation_utils_test.ts, test/asset-swapper/quote_simulation_test.ts
* Besides, a few tests, the only `GasSchedule` instance ever used is `DEFAULT_GAS_SCHEDULE` so it is not necessary for `GetMarketOrdersOpts` to have `GasSchedule`(an option that is never used).
* Require `GasSchedule` to have gas schedule for all sources (remove `Partial`). 
* No-op refactoring. Passes existing test suite.
=> chore: Make `GasSchedule` not `Partial` and remove it from `GetMarketOrdersOpts` [LIT-690]

src/asset-swapper/types.ts, src/asset-swapper/utils/market_operation_utils/constants.ts, src/asset-swapper/utils/market_operation_utils/index.ts, src/config.ts
* Remove `EXCLUDED_SOURCES` and `EXCLUDED_FEE_SOURCES` as there is no reason to maintain both chain specific included source list as well as excluded source list.
* Remove `excludedFeeSources`  from `GetMarketOrdersOpts` as it's no longer used.
=> chore: Clean up excluded sources and excluded fee sources [LIT-690]

src/app.ts, src/config.ts, src/constants.ts, src/db_connection.ts, src/ormconfig.ts, src/runners/http_service_runner.ts, src/runners/http_sra_service_runner.ts, src/runners/rfq_maker_balance_cache_runner.ts, src/services/orderbook_service.ts, src/services/postgres_rfqt_firm_quote_validator.ts, src/types.ts, src/utils/no_op_orderbook.ts, src/utils/rfq_dyanmic_blacklist.ts, test/orderbook_service_test.ts, test/sra_test.ts, test/swap_test.ts, test/test_env, test/utils/db_connection.ts
* Make PostgreSQL an optional dependency of a `/swap`
* Exit with an error when PostgreSQL is required (`/orderbook`, `/sra`)
* [Simbot without local PostgreSQL instance](https://metabase.spaceship.0x.org/dashboard/186?run_id=ethereum-no-pg)
* [Simbot with local PostgreSQL instance](https://metabase.spaceship.0x.org/dashboard/186?run_id=ethereum-with-pg)
=> chore: Make PostgreSQL an optional dependency [LIT-708]

src/asset-swapper/types.ts, src/asset-swapper/utils/market_operation_utils/constants.ts, src/asset-swapper/utils/market_operation_utils/index.ts, src/config.ts
Remove `excludedFeeSources` from `GetMarketOrdersOpts` 
* `excludedFeeSources` is a no-op as there is no overlap between `EXCLUDED_FEE_SOURCES` and 
`BUY_SOURCE_FILTER_BY_CHAIN_ID`/`SELL_SOURCE_FILTER_BY_CHAIN_ID`
* [sanity simbot run](https://metabase.spaceship.0x.org/dashboard/186?run_id=ethereum-excl-fee-sources&adjusted_amount_bought_win_tolerance__bps_=1.0)
=> chore: Remove `excludedFeeSources` from `GetMarketOrdersOpts` [LIT-690]

package.json, src/asset-swapper/swap_quoter.ts, src/asset-swapper/utils/market_operation_utils/index.ts, src/config.ts, test/asset-swapper/market_operation_utils_test.ts
* Remove a hack around creating a dummy limit order to pass down token addresses.
* [sanity check simbot run](https://metabase.spaceship.0x.org/dashboard/186?run_id=ethereum-dummy-limit)
=> chore: Make `getOptimizerResultAsync` to explicitly take token addresses [LIT-690]

src/config.ts, src/handlers/swap_handlers.ts
Use correct 0x gas api url for Arbitrum swaps.
https://linear.app/0xproject/issue/LIT-724/arbitrum-swap-error
When estimating gas for Arbitrum swaps, we were erroneously using the Mainnet instance of the gas api since that is the default. Pass in the gas api url from the environment variable to get the correct gas api instance.
Tested against local API to see gas estimates in the ~2m range and verified on-chain this is about right.
Before this change, gas prices were coming from Mainnet, which are about 100x more expensive, resulting in a much too low of an estimate for Arbitrum since we divide by the gas price.
-   [ ] All dependent changes (e.g. RFQ …
=> fix: Use correct 0x gas api url for arbitrum swaps

src/asset-swapper/utils/market_operation_utils/index.ts
RFQt v2 prices are not included in indicative quotes when passing to optimizer in for `/price`
=> fix: Include RFQt v2 prices as indicative quotes when passing to optimizer

src/asset-swapper/swap_quoter.ts, src/asset-swapper/types.ts, src/asset-swapper/utils/market_operation_utils/orders.ts, src/asset-swapper/utils/market_operation_utils/path.ts
* Remove unused `sourcePathId` in `OptimizedMarketBridgeOrder`
* Simplify `calculateTwoHopQuoteInfo`
* Define `FillBase` instead of using `Omit<Fill, ...>`.
* Rename `cleanFillForExport` to `toFillBase` and make it type-safe
=> chore: Clean up various `OptimizedOrder` related code [LIT-690]

src/asset-swapper/utils/market_operation_utils/index.ts, src/asset-swapper/utils/market_operation_utils/orders.ts, src/asset-swapper/utils/market_operation_utils/path.ts, test/asset-swapper/utils/market_operations_utils/path_test.ts
* Remove states (adjustedSize and sourceFlags) in `Path` by computing them before initializing `Path` 
* Add a unit test for `sourceFlags`
* Added a unit test.
=> chore: Remove states in `Path` [LIT-690]

src/asset-swapper/types.ts, src/asset-swapper/utils/market_operation_utils/index.ts, src/asset-swapper/utils/market_operation_utils/path.ts, src/asset-swapper/utils/market_operation_utils/path_optimizer.ts, src/asset-swapper/utils/market_operation_utils/types.ts, test/asset-swapper/utils/market_operations_utils/path_test.ts
* Replace `Path.finalize` and `FinalizedPath` with `Path.createOrders`
* Added some unit tests
=> chore: Replace `Path.finalize` and `FinalizedPath` with `Path.createOrders` [LIT-690]

src/asset-swapper/utils/market_operation_utils/sampler_operations.ts, src/asset-swapper/utils/market_operation_utils/types.ts, test/asset-swapper/quote_report_generator_test.ts, test/asset-swapper/utils/market_operations_utils/path_optimizer_test.ts
* Simplify `MultiHopFillData`
* `firstHopSource` and `secondHopSource` does not need to be `SourceQuoteOperation`
* [Sanity simbot run](https://metabase.spaceship.0x.org/dashboard/186?run_id=two-hop-fill-data&adjusted_amount_bought_win_tolerance__bps_=1.0)
=> chore: Simplify `MultiHopFillData` [LIT-690]

src/asset-swapper/quote_consumers/exchange_proxy_swap_quote_consumer.ts, src/asset-swapper/swap_quoter.ts, src/asset-swapper/types.ts, src/asset-swapper/utils/market_operation_utils/path.ts, test/asset-swapper/exchange_proxy_swap_quote_consumer_test.ts, test/asset-swapper/utils/market_operations_utils/path_test.ts, test/utils/mocks.ts
*  Move `slipNonNativeOrders` to `Path.createSlippedOrders`
* Added unit tests
=> chore: Move `slipNonNativeOrders` to `Path` [LIT-690]

src/asset-swapper/quote_consumers/exchange_proxy_swap_quote_consumer.ts, src/asset-swapper/quote_consumers/quote_consumer_utils.ts, src/asset-swapper/swap_quoter.ts, src/asset-swapper/types.ts, test/asset-swapper/exchange_proxy_swap_quote_consumer_test.ts, test/utils/mocks.ts
*  Remove `isTwoHop` from `SwapQuoteBase`
* Passes existing unit / integration tests.
=> chore: Remove `isTwoHop` from `SwapQuoteBase` [LIT-690]

src/asset-swapper/quote_consumers/exchange_proxy_swap_quote_consumer.ts, src/asset-swapper/quote_consumers/quote_consumer_utils.ts, src/asset-swapper/swap_quoter.ts, src/asset-swapper/types.ts, src/services/swap_service.ts, src/types.ts, test/asset-swapper/exchange_proxy_swap_quote_consumer_test.ts, test/utils/mocks.ts
* Remove `orders` in `SwapQuoteBase` 
* Passes existing unit/integration tests.
* [Sanity simbot run](https://metabase.spaceship.0x.org/dashboard/186?run_id=2023-01-rm-orders-2)
=> chore: Remove `orders` in `SwapQuoteBase` [LIT-690]

src/asset-swapper/swap_quoter.ts, src/asset-swapper/types.ts, src/asset-swapper/utils/quote_simulation.ts, test/asset-swapper/exchange_proxy_swap_quote_consumer_test.ts, test/utils/mocks.ts
*  Remove unused `feeTakerAmount` in `SwapQuoteInfo`
* Passes existing tests.
=> chore: Remove unused `feeTakerAmount` in `SwapQuoteInfo` [LIT-690]

src/asset-swapper/types.ts, src/asset-swapper/utils/market_operation_utils/orders.ts, src/asset-swapper/utils/market_operation_utils/path.ts, test/asset-swapper/utils/market_operations_utils/path_test.ts
* Implement `Path.getOrdersByType` which returns orders grouped by type (native, multihop, DEX single hop).
* Updated unit tests.
=> chore: Implement `Path.getOrdersByType` [LIT-690]

src/asset-swapper/types.ts, src/asset-swapper/utils/market_operation_utils/orders.ts, src/asset-swapper/utils/market_operation_utils/path.ts, src/asset-swapper/utils/quote_info.ts, test/asset-swapper/exchange_proxy_swap_quote_consumer_test.ts, test/asset-swapper/utils/market_operations_utils/path_test.ts, test/asset-swapper/utils/market_operations_utils/quote_info_test.ts
* Use `Path.getOrdersByType` in `calculateQuoteInfo`
* Updated unit tests.
=> chore: Use `Path.getOrdersByType` in `calculateQuoteInfo` [LIT-690]

src/asset-swapper/index.ts, src/asset-swapper/quote_consumers/quote_consumer_utils.ts, src/asset-swapper/types.ts, src/asset-swapper/utils/quote_info.ts, src/asset-swapper/utils/quote_simulation.ts, src/services/swap_service.ts, src/utils/service_utils.ts, test/asset-swapper/utils/market_operations_utils/quote_info_test.ts, test/service_utils_test.ts, test/utils/mocks.ts
* Modify to `calculateQuoteInfo` to handle Multiplex+MultiHop
* Change the schema of `SwapQuoteOrdersBreakdown` 
* Rename it `SwapQuoteSourceBreakdown`
* Modify `convertSourceBreakdownToArray` to handle new `SwapQuoteOrdersBreakdown`
* Rename it to `convertToLiquiditySource`
* Modified existing tests for `calculateQuoteInfo`
* Added unit tests for `convertToLiquiditySources`
* [Sanity simbot run](https://metabase.spaceship.0x.org/dashboard/186?run_id=2023-01-source-breakdown-3)
=> chore: Modify `calculateQuoteInfo` to handle Multiplex+MultiHop [LIT-690]

src/asset-swapper/quote_consumers/exchange_proxy_swap_quote_consumer.ts, src/asset-swapper/types.ts, src/services/swap_service.ts, test/asset-swapper/exchange_proxy_swap_quote_consumer_test.ts
A few minor clean up related to `SwapQuoteConsumer`.
* Make `transformerNonces` private
* Make `SwapQuoteConsumer.getCalldataOrThrowAsync` not `async`
* Make `SwapService._getSwapQuotePartialTransactionAsync` not `async`
* Updated unit tests
=> chore: Make `SwapQuoteConsumer.getCalldataOrThrowAsync` not `async` [LIT-760]

contracts/src/UniswapV3Sampler.sol
Updating the UniswapV3 buy sampler to have the correct pool path order. Previously, the pool path seems to have been reversed resulting in incorrect fees being chosen when building a UniswapV3 buy path. This PR adjusts the pool path to have the correct order
[Mainnet](https://metabase.spaceship.0x.org/dashboard/186?run_id=UniswapV3-buy-sampler-reverse-fix-p3&adjusted_amount_bought_win_tolerance__bps_=1.0)
=> fix: incorrect UniswapV3 buy sampler pool path order [LIT-765]

src/asset-swapper/utils/market_operation_utils/constants.ts
Arbitrum token adjacency graph was not previously defined. 
* [sanity simbot run](https://metabase.spaceship.0x.org/dashboard/186?run_id=kyu-arb-usds-fix)
=> fix: Add missing Arbitrum token adjacency graph [LIT-767]

src/asset-swapper/utils/market_operation_utils/constants.ts
* Do not use `valueByChainId` for token adjacency graph and the intermediate token list.
* This change will force those to be defined when a new chain is added.
=> refactor: Require token adjacency graph to be explicitly defined for each chain [LIT-768]

src/asset-swapper/constants.ts, src/asset-swapper/index.ts, src/asset-swapper/quote_consumers/exchange_proxy_swap_quote_consumer.ts, src/asset-swapper/types.ts, src/services/swap_service.ts, test/asset-swapper/exchange_proxy_swap_quote_consumer_test.ts
* Use `ExchangeProxyContractOpts` directly instead of `SwapQuoteGetOutputOpts`
* Define `ERC20Transformation` interface
* Updated unit tests
=> chore: Simplify `SwapQuoteConsumer.getCalldataOrThrow` interface [LIT-760]

src/asset-swapper/constants.ts, src/asset-swapper/index.ts, src/asset-swapper/quote_consumers/exchange_proxy_swap_quote_consumer.ts, src/asset-swapper/quote_consumers/quote_consumer_utils.ts, src/asset-swapper/types.ts, src/services/swap_service.ts, test/asset-swapper/exchange_proxy_swap_quote_consumer_test.ts, test/asset-swapper/utils/market_operations_utils/quote_info_test.ts
`MultiplexFeature`'s multihop logic assumed that there can be only single two hop order. As that may not be the case in the future modify the compatibility checking and encoding logic to account for multiple two hop orders.
* Passes existing unit test
=> chore: Do not use `MultiplexFeature` on multiple two hop orders [LIT-637]

src/asset-swapper/quote_consumers/exchange_proxy_swap_quote_consumer.ts, src/asset-swapper/quote_consumers/quote_consumer_utils.ts, src/asset-swapper/quote_consumers/types.ts, src/services/swap_service.ts, test/asset-swapper/exchange_proxy_swap_quote_consumer_test.ts
Simplify `ExchangeProxySwapQuoteConsumer` constructor
* Move dependency creations logic to the static factory method
* Updated unit test to use the static factory method.
=> refactor: Simplify `ExchangeProxySwapQuoteConsumer` constructor [LIT-760]

src/asset-swapper/quote_consumers/exchange_proxy_swap_quote_consumer.ts, src/asset-swapper/quote_consumers/feature_rules/feature_rule_registry.ts, src/asset-swapper/quote_consumers/feature_rules/transform_erc20_rule.ts, src/asset-swapper/quote_consumers/feature_rules/types.ts, src/asset-swapper/quote_consumers/quote_consumer_utils.ts, test/asset-swapper/quote_consumer/feature_rules/transform_erc20_rule_test.ts
Introduce `FeatureRule` which is responsible for determining whether a quote is compatible for a exchange proxy feature. 
* Move `TransformERC20` calldata generation logic into a rule
* Existing `ExchangeProxySwapQuoteConsumer` tests have been moved to `transform_erc20_rule.ts` 
* Unfortunately, there were no tests for non-`TransformERC20` features. 
* [Simbot run](https://metabase.spaceship.0x.org/dashboard/186?run_id=2023-01-ep-consumer-4)
=> refactor: Introduce `FeatureRule` and move `TransformERC20` calldata generation logic into a rule [LIT-760]

src/asset-swapper/quote_consumers/feature_rules/abstract_feature_rule.ts, test/asset-swapper/quote_consumer/feature_rules/transform_erc20_rule_test.ts
* Fix `ethAmount` in `AbstractFeatureRule.getSwapContext`
* Added a unit test.
* [Simbot](https://metabase.spaceship.0x.org/dashboard/186?run_id=2022-jan-eth-amount-fix&adjusted_amount_bought_win_tolerance__bps_=1.0)
=> fix: Fix `ethAmount` in `AbstractFeatureRule.getSwapContext`

test/asset-swapper/quote_consumer/feature_rules/transform_erc20_rule_test.ts, test/asset-swapper/test_utils/decoders.ts, test/asset-swapper/test_utils/test_data.ts
The main goal was to replace random test objects with deterministic ones and and also improve readability. 
* Get rid of most of random tests objects in `transform_erc20_rule_test.ts`
* Remove a redundant affiliate fee (gasless) test 
* Test-only changes.
=> refactor: Replace most of random tests objects in `transform_erc20_rule_test.ts` [LIT-760]

src/asset-swapper/utils/market_operation_utils/constants.ts
Temporarily disable `Dystopia` as it seems to be causing a lot of reverts.
=> fix: Temporarily disable `Dystopia` on Polygon

src/asset-swapper/quote_consumers/feature_rules/transform_erc20_rule.ts, src/asset-swapper/types.ts, test/asset-swapper/quote_consumer/feature_rules/transform_erc20_rule_test.ts, test/asset-swapper/test_utils/test_data.ts
Implement Multiplex+Multihop calldata generation logic in `TransformERC20Rule`
* Factor out `FillQuoteTransformer` and `PayTakerTransformer` for improved readability.
* Refactor `test_data.ts`
* Check whether the quote is sell quote before applying `shouldSellEntireBalance` in `createTwoHopTransformations`
* Added unit tests.
* [Simbot run](https://metabase.spaceship.0x.org/dashboard/186?run_id=2023-multiplex-multihop-calldata-4&adjusted_amount_bought_win_tolerance__bps_=5)
=> feat: Implement Multiplex+Multihop calldata generation logic [LIT-637]

src/asset-swapper/utils/market_operation_utils/constants.ts
Reverts 0xProject/0x-api#1206. Can add this back once RFQt is ready for Polygon.
=> fix: revert "chore: add native to polygon source filter"

src/asset-swapper/utils/market_operation_utils/index.ts, src/asset-swapper/utils/market_operation_utils/path_optimizer.ts, src/asset-swapper/utils/market_operation_utils/sampler_operations.ts, src/asset-swapper/utils/market_operation_utils/types.ts, src/asset-swapper/utils/quote_report_generator.ts, test/asset-swapper/utils/market_operations_utils/path_optimizer_test.ts
Add a partial `Multiplex+MultiHop` support in `SamplerOperations` and `PathOptimizer`
* NOTE: this only adds `Multiplex+MultiHop` supports to some of the components. It is a no-op change until `MarketOperationUtils` actually starts sampling multiple amounts for two-hop.
* Added a unit test for `PathOptimizer`
* [simbot run](https://metabase.spaceship.0x.org/dashboard/186?run_id=2023-jan-mult-two-hop-samples&adjusted_amount_bought_win_tolerance__bps_=1.0)
=> feat: Add a partial `Multiplex+MultiHop` support in `SamplerOperations` and `PathOptimizer` [LIT-637]

src/asset-swapper/utils/market_operation_utils/index.ts, test/asset-swapper/market_operation_utils_test.ts
* Move `getMarket{Sell|Buy}Liquidity` to `getMarketLiquidity`
* Make `generateOptimizedOrders` not `async`
* Factor out phase 1 routing in to a method
* [simbot](https://metabase.spaceship.0x.org/dashboard/186?run_id=2023-jan-market-opts-0&adjusted_amount_bought_win_tolerance__bps_=5)
=> refactor: Refactor `MarketOperationUtils` [LIT-637]

src/config.ts, src/services/swap_service.ts
Restrict positive slippage collection to those in a configured set.
Simbot run looks good
=> chore: only collect positive slippage fees on allowed buy tokens

src/asset-swapper/quote_consumers/exchange_proxy_swap_quote_consumer.ts, src/asset-swapper/utils/market_operation_utils/constants.ts, src/asset-swapper/utils/market_operation_utils/orders.ts, src/asset-swapper/utils/market_operation_utils/types.ts, src/samplers/uniswapv3_sampler.ts
These types will be reused for other tick-based AMMs. Rename to more generic names.
=> chore: Rename UniswapV3 fill data related types

src/asset-swapper/swap_quoter.ts, src/asset-swapper/types.ts, src/asset-swapper/utils/market_operation_utils/index.ts, src/asset-swapper/utils/market_operation_utils/types.ts, src/handlers/swap_handlers.ts, src/services/meta_transaction_service.ts, src/services/swap_service.ts, src/types.ts, src/utils/sampler_metrics.ts, test/asset-swapper/comparison_price_test.ts, test/asset-swapper/test_utils/test_data.ts, test/swap_test.ts, test/utils/mocks.ts
When query param `debug=true` is set some debug data (sampler gas usage to begin with) is returned as a part of the response.
Example: 
```
"debugData": {
"samplerGasUsage": 108263697
},
```
* [Simbot run](https://metabase.spaceship.0x.org/dashboard/186?run_id=2023-feb-swap-debug&adjusted_amount_bought_win_tolerance__bps_=1.0)
=> feat: Introduce swap debug mode [LIT-841]

package.json, test/asset-swapper/utils/market_operations_utils/gas_price_utils_test.ts, yarn.lock
The server mocking library `msw` does not support Node 18, which was first released in 2019 and has been the active node LTS version for four months. (see https://github.com/mswjs/msw/issues/1388)
Remove this library and replace with the already-in-place solution of TypeMoq.
=> refactor: Remove msw from gas price utils test

src/config.ts, src/handlers/swap_handlers.ts, src/options.ts, src/services/swap_service.ts, test/swap_test.ts
* As `logger.ts` depends on `config.ts`, `config.ts` depending on `asset-swapper` makes it difficult to avoid circular dependency.
* n/a
=> chore: Move `asset-swapper` options out of `config.ts` [LIT-708]

src/asset-swapper/quote_consumers/multiplex_encoders.ts
Fix the enum value of `MultiplexSubcall` in `multiplex_encoder.ts` (regression from #1074 which deleted one of the enum values and thereby shifted the subsequent enum value by -1).
=> fix: Fix enum value of `MultiplexSubcall` in the encoder

src/asset-swapper/swap_quoter.ts, src/asset-swapper/types.ts, src/logger.ts, src/services/orderbook_service.ts, src/services/swap_service.ts
* Move orderbook specific log function out of `logger.ts`
* Use standard logger in `swap_quoter.ts`
=> refactor: Use the standard logger in `swap_quoter.ts` [LIT-852]

src/utils/sampler_metrics.ts
* Fix `help` for `sampler_blocknumber`
* Shorten `help` for others.
=> fix: Fix `help` for `sampler_blocknumber`

src/asset-swapper/utils/market_operation_utils/constants.ts
The Saddle BTC pool on mainnet is paused, leading to a high revert rate.
=> fix: removing paused Saddle BTC pool [LIT-857]
